/* ==========================================================================
   FERME VALLÉE (jeu 22) — libellés bilingues INTERNES au jeu.
   ==========================================================================
   Le jeu est très riche en texte (boutique, bac, aides, toasts). Pour ne pas
   gonfler lib/i18n.js (STR) de plusieurs dizaines de clés et risquer une
   asymétrie FR/EN, ces libellés propres au jeu vivent ici, en un dictionnaire
   { fr, en } auto-porté. Seuls le NOM et le TAG de la carte (nameFerme /
   tagFerme) sont dans lib/i18n.js, car page.js en a besoin hors du composant.

   Règle site : AUCUN tiret quadratin dans le texte FR joueur.
   `fstr(lang)` renvoie le bon jeu de libellés ; les fonctions acceptent des
   paramètres (niveau d'outil, gain, etc.).
   ========================================================================== */

export const FERME_STR = {
  fr: {
    // --- Mise à jour gare 2026-07 (créatures marines, canards, gare, visiteurs, saisons) ---
    seaCaught: (n) => `Prise rare : ${n} !`,
    seaBite: (n) => `Quelque chose d'inhabituel mord... ${n} ?!`,
    stationName: "Gare du village",
    promptStation: "E : panneau d'annonces de la gare",
    adsTitle: "🚉 Panneau d'annonces",
    adsIntro: "Affiche ce que la ferme vend pour attirer des visiteurs par le train. Chaque nouvelle annonce coûte des frais d'affichage (caisse commune). Les prix ne sont pas affichés : les visiteurs font leurs offres.",
    adsFee: (c) => `Frais : ${c} or par nouvelle annonce`,
    adsSave: "Afficher les annonces",
    adsSaved: (c) => c > 0 ? `Annonces affichées (${c} or de frais).` : "Annonces mises à jour.",
    adCatCrops: "🌾 Cultures et légumes",
    adCatAnimal: "🥚 Produits de la ferme",
    adCatFish: "🐟 Poissons et pêche",
    adCatResources: "🪵 Bois et pierre",
    adsBlacklistTitle: "🚫 Liste noire",
    adsBlacklistEmpty: "Personne n'est banni pour l'instant.",
    adsBlacklistHint: "Un visiteur banni ne reviendra plus jamais par le train.",
    visitorArrived: (n) => `🚂 ${n} arrive par le train !`,
    visitorsArrived: (ns) => `🚂 Des visiteurs arrivent par le train : ${ns} !`,
    visitorLeftChat: (n) => `${n} repart vers la gare.`,
    promptVisitor: (n) => `Q : parler à ${n}`,
    visitorPanelTitle: (n) => `🧳 ${n}`,
    visitorWantsBuy: (n, q, c, p) => `${n} veut acheter ${q} × ${c} et propose ${p} or pièce.`,
    visitorRichBonus: (b) => `Et ${b} or de prime si l'affaire est conclue !`,
    visitorWantsChat: (n) => `${n} est simplement venu(e) voir la ferme et discuter.`,
    visitorDemand: (n, g0) => `${n} exige ${g0} or de la caisse, sinon nos récoltes et notre or vont y passer !`,
    visitorUrgent: "URGENT",
    visitorAccept: "Conclure la vente",
    visitorChatBtn: "Discuter",
    visitorPayBtn: (g0) => `Payer ${g0} or`,
    visitorRefuseBtn: "Refuser",
    visitorBlacklistBtn: "Bannir ce visiteur",
    visitorNotEnough: "Tu n'as pas assez de cette culture sur toi.",
    visitorDealDone: (n, g0) => `Vente conclue avec ${n} : +${g0} or dans la caisse !`,
    visitorChatDone: (n) => `${n} a apprécié la discussion. (amitié +1)`,
    visitorPaid: (n, g0) => `${n} empoche ${g0} or et repart. Quel personnage...`,
    visitorRelation: (r) => `Amitié : ${r}`,
    visitorStock: (h, n) => `Tu portes ${h} / ${n} demandés.`,
    visitorEasyNote: "Commande facile : c'est déjà en stock, petit prix.",
    visitorPrepNote: "Commande à préparer : plus longue, mieux payée.",
    visitorRewardGift: (g) => `En plus de l'or, ${g} si l'affaire est conclue !`,
    visitorGiftGranted: (n, g) => `🎁 ${n} laisse un cadeau : ${g} !`,
    visitorGiftQueued: (n, g) => `🎁 ${n} promet un cadeau : ${g}. Il sera livré dès que possible !`,
    visitorGiftPromised: (n, g) => `🎁 ${n} promet de t'envoyer un cadeau : ${g}. Il arrivera dans quelques minutes !`, // zip 250
    visitorGiftDelivered: (n, g) => `🎁 Le cadeau promis par ${n} vient d'arriver dans ton sac : ${g} !`, // zip 250
    giftSeed: (s) => `des graines uniques (${s})`,
    giftDecor: (d) => `une décoration unique (${d})`,
    giftPet: (pt) => `un animal de compagnie (${pt})`,
    meetBtn: "Rejoindre à la mairie",
    notifMore: (n) => `+${n} autre(s) visiteur(s) en attente`,
    visitorChatSaid: (n, l0) => `${n} : ${l0}`,
    visitorChatLines: [
      [
        "Belle journée pour une balade, non ?",
        "Le train était plein aujourd'hui, votre ferme fait parler d'elle !",
        "Ça sent bon la terre fraîche par ici.",
        "Je ne fais que passer, mais l'endroit est charmant.",
      ],
      [
        "Content(e) de vous revoir ! Je pense souvent à cette ferme.",
        "J'ai raconté vos récoltes à tout le wagon, ils étaient jaloux.",
        "Vous m'offrez toujours un bon moment ici.",
        "La place de la mairie est mon coin préféré de la vallée.",
      ],
      [
        "Entre amis, pas besoin de marchander longtemps !",
        "Je garde toujours une place pour vous dans mes bagages... et un cadeau parfois.",
        "Cette ferme, c'est un peu ma deuxième maison maintenant.",
        "Si vous passez un jour à Valley Town, ma porte vous est ouverte.",
      ],
    ],
    visitorThanks: (n) => `${n} vous remercie et flâne encore un peu sur la place.`,
    visitorHomeChat: (n) => `${n} rentre à la gare, ravi(e) de sa visite.`,
    visitorArrivalGift: (n, g) => `🎁 ${n} est venu(e) avec un cadeau : ${g} !`,
    visitorTotal: (t) => `${t} or au total`,
    visitorPerUnit: (p) => `${p} or / unité`,
    visitorPocket: "En poche",
    visitorCloseBtn: "Plus tard",
    visitorChatTitle: "Discussion",
    promptTrainRide: "E : prendre le train pour Valley Town",
    promptTrainBack: "E : reprendre le train vers la ferme",
    trainToTownToast: "🚆 Bienvenue à Valley Town !",
    trainToFarmToast: "🚆 Retour à la ferme.",
    promptTownHouse: (n) => `Maison de ${n}`,
    promptTownHouseSale: "Maison à vendre",
    toastYourHouse: "C'est votre maison à Valley Town. Aménagement intérieur à venir !",
    toastTheirHouse: (n) => `C'est la maison de ${n}.`,
    toastHouseSale: "Cette maison attend un nouveau fermier.",
    townSaleSign: "À vendre",
    cropTipReady: "mûr !",
    cropTipWater: "à arroser",
    adsGiftsTitle: "🎁 Cadeaux promis",
    adsGiftsEmpty: "Aucun cadeau en attente.",
    adsGiftRow: (g, n) => `${g} (promis par ${n})`,
    hostileDamageChat: (n, g0, cr) => `⚠️ ${n} a frappé : ${g0} or volés, ${cr} culture(s) saccagée(s) ! Rassemblez-vous pour réparer !`,
    repairTitle: "🛠️ Réparer les dégâts",
    repairIntro: (n) => `${n} a saccagé la ferme ! Clique quand le curseur est dans la zone verte. Chaque joueur qui réussit rapproche la réparation totale.`,
    repairHits: (h, t) => `Réussites : ${h} / ${t}`,
    repairWin: "Bien joué ! Ta part de la réparation est faite.",
    repairFail: "Raté... réessaie si la fenêtre est encore ouverte.",
    repairProgress: (w0, n0) => `Réparation : ${w0} / ${n0} joueur(s). Encore un effort !`,
    repairDoneChat: (g0, cr) => `✅ Dégâts réparés ensemble : ${g0} or récupérés, ${cr} culture(s) replantée(s) !`,
    repairExpired: "La fenêtre de réparation est passée... les dégâts sont définitifs.",
    stayTitle: (n) => `🏠 ${n} veut s'installer !`,
    stayProposal: (n, j) => `${n} propose de rester vivre à la ferme et de contribuer : "${j}". Le vote doit être unanime. En cas d'égalité, un dé décidera.`,
    voteYes: "✅ Pour",
    voteNo: "❌ Contre",
    voteWaiting: "Vote enregistré, en attente des autres joueurs...",
    voteStayChat: (n) => `🎉 Vote unanime : ${n} s'installe à la ferme !`,
    residentStarted: (n, job) => `${n} s'installe dans une maison à vendre et se met au travail : ${job}.`,
    // Zip 252 : artisans / ateliers / produits.
    residentMovedIn: (n, job) => `🏡 ${n} a emménagé sur la ferme et va ${job}.`,
    residentNoRoom: "Plus de maison libre pour accueillir un résident.",
    artisanNoResident: "Il faut d'abord que l'artisan correspondant vive chez toi.",
    artisanBuilt: (b) => `🔨 ${b} construit(e) ! L'artisan peut se mettre à produire.`,
    buildingName: (bid) => ({ beehive: "Ruche", fromagerie: "Fromagerie", bakery: "Boulangerie", sawmill: "Scierie" }[bid] || bid),
    craftName: (item) => ({ honey: "Pot de miel", cheeseWheel: "Roue de fromage", cheesePortion: "Part de fromage", pastry: "Pâtisserie" }[item] || item),
    craftSold: (name, n, gain) => `Vente : ${n} × ${name} (+${gain} or) ! Caisse commune enrichie.`,
    cheeseCut: (w, p) => `🧀 ${w} roue(s) découpée(s) en ${p} parts.`,
    promptResident: (n) => `Q — parler à ${n}`,
    recruitAsk: "Proposer d'emménager",
    residentGreet: (n, job) => `Bonjour ! Moi c'est ${n}. Mon métier, c'est ${job}.`,
    // Zip 262 (demande Guillaume) : les visiteurs À SKILL s'annoncent
    // clairement (« Je suis bûcheron et je souhaite vous aider à… »).
    skillLabel: (sk) => ({ beekeeper: "apiculteur", cheesemaker: "fromager", baker: "boulanger-pâtissier", lumberjack: "bûcheron", voyager: "marchand voyageur" }[sk] || sk),
    skillPitch: (sk, n) => ({
      beekeeper: `Bonjour ! Moi c'est ${n}, je suis apiculteur et je souhaite vous aider à récolter et mettre en pot le miel de la ferme.`,
      cheesemaker: `Bonjour ! Moi c'est ${n}, je suis fromager et je souhaite vous aider à transformer votre lait en fromage.`,
      baker: `Bonjour ! Moi c'est ${n}, je suis boulanger-pâtissier et je souhaite vous aider à cuire pâtisseries et gâteaux.`,
      lumberjack: `Bonjour ! Moi c'est ${n}, je suis bûcheron et je souhaite vous aider à abattre les arbres et casser les rochers.`,
      voyager: `Bonjour ! Moi c'est ${n}, je suis marchand voyageur et je souhaite parcourir le monde pour vous rapporter des denrées rares.`,
    }[sk] || `Bonjour ! Moi c'est ${n}.`),
    residentNeedBuilding: (b) => `Construis-moi une ${b} (achetable en or à la boutique) et je produirai pour la ferme !`,
    residentBuildingReady: (b) => `Ma ${b} tourne. Garde nos stocks remplis et je fais le reste !`,
    residentLumberjackLine: "Je coupe du bois et casse des cailloux toute la journée — tout va dans notre réserve commune.",
    residentCloseBtn: "À plus tard",
    // Zip 253 : fiche résident enrichie + onglet Employés.
    residentRoleTitle: "Production",
    residentNotWorkingYet: "Pas encore d'atelier — je m'installe.",
    residentProdHoney: (n) => `Ruche en route — ${n} pot(s) de miel en réserve.`,
    residentProdCheese: (w, p) => `Fromagerie active — ${w} roue(s), ${p} part(s) au frais.`,
    residentProdPastry: (n) => `Le four tourne — ${n} pâtisserie(s) prête(s).`,
    residentProdWood: (w, s) => `Réserve commune : ${w} bois, ${s} pierre(s) rentrés.`,
    residentSeeBtn: "Voir",
    // Zip 258 : alerte pâtissière (rupture d'ingrédients en journée).
    bakeryAlertShort: "⚠️ Ingrédients manquants",
    bakeryAlertLine: "⚠️ Four à l'arrêt — il me manque des ingrédients !",
    bakeryAlertTitle: "La pâtissière a besoin d'ingrédients",
    bakeryAlertMsg: "Impossible de continuer : il me faut 1 lait, 1 farine et 6 œufs par fournée. Remplis nos stocks et je m'y remets aussitôt !",
    bakeryAlertToast: "🍰 La pâtissière n'a plus d'ingrédients — production stoppée.",
    bakeryNotifSee: "Voir",
    // Zip 258 : Eduardo Da Fonseca, commerçant grand voyageur.
    voyagerStatusHome: "De retour au village — prêt à repartir en voyage.",
    voyagerStatusAway: (d) => `En voyage — retour dans ~${d}.`,
    voyagerOrderBtn: "Commander un voyage",
    voyagerSellBtn: "Revendre les produits",
    voyagerOrderTitle: "🌍 Commander un voyage à Eduardo",
    voyagerOrderHint: "Choisis les produits du monde à rapporter. Plus la région est lointaine, plus c'est cher et plus le voyage est long. Payé d'avance.",
    voyagerTripDays: (d) => `${d} jour(s) de voyage`,
    voyagerUnitCost: (c) => `${c} or/unité`,
    voyagerTotal: (c) => `Total : ${c} or`,
    voyagerSendBtn: "Envoyer Eduardo",
    voyagerCancelBtn: "Annuler",
    voyagerEmptyOrder: "Ajoute au moins un produit.",
    voyagerDeparted: (d) => `🐎 Eduardo part en voyage (retour dans ${d}). Bon vent !`,
    voyagerBusyToast: "Eduardo est déjà en voyage.",
    voyagerReturned: (goods) => `🧳 Eduardo est rentré avec : ${goods} !`,
    voyagerReturnNotifTitle: "Eduardo est de retour !",
    voyagerSurpriseTag: " (+ surprise)",
    voyagerSellTitle: "🌍 Produits du monde à revendre",
    voyagerSellRow: (name, n) => `${name} × ${n}`,
    worldGoodName: (key) => ({ vanilla: "Gousse de vanille", coffee: "Café", cinnamon: "Cannelle", cocoa: "Cacao", pineapple: "Ananas", coconut: "Noix de coco" }[key] || key),
    voyagerProdLine: (n) => n > 0 ? `Comptoir du voyageur — ${n} produit(s) du monde en réserve.` : "Commerçant grand voyageur — prêt à partir.",
    // Zip 259 : exclusion d'un résident + retour de l'ex-résident.
    residentsSectionTitle: "Résidents",
    kickBtn: "Voter l'exclusion",
    kickTally: (n, m) => `Exclusion : ${n}/${m} voix`,
    kickedChat: (name) => `👋 ${name} a été exclu(e) et libère sa maison.`,
    kickVotedToast: "Ton vote d'exclusion est enregistré.",
    exileReturnChat: (name) => `${name} est revenu(e) au village et demande à vous parler…`,
    pleaTitle: (name) => `${name} est de retour`,
    pleaAccept: "Réintégrer",
    pleaRefuse: "Refuser",
    notifPlea: "revient vous parler",
    exileReacceptedChat: (name) => `🏡 ${name} réemménage — content(e) de le/la revoir !`,
    exileRefusedChat: (name) => `${name} repart pour de bon.`,
    exilePlea: (mood, vi) => (({
      touching: [
        "…Je ne comprends pas. J'étais si bien parmi vous. Est-ce que je peux revenir ? Je ferai des efforts, c'est promis.",
        "Vous m'avez manqué chaque jour. Cette ferme, c'était ma famille. Accordez-moi une seconde chance, je vous en supplie.",
        "Je n'ai pas fermé l'œil depuis mon départ. Dites-moi ce que j'ai mal fait et je le corrigerai, mais reprenez-moi.",
        "J'ai marché des heures pour revenir. Mon cœur est resté ici, avec vous. Laissez-moi rentrer à la maison…",
      ],
      bitter: [
        "Alors on jette les gens comme de vieux outils ? Vous le regretterez, croyez-moi.",
        "Je reviens, mais pas pour mendier. Vous avez été injustes, et vous le savez parfaitement.",
        "J'ai tout donné pour cette ferme, et voilà comment vous me remerciez. Minable.",
        "Ne croyez pas que j'oublierai. On récolte toujours ce que l'on sème.",
      ],
      healthy: [
        "Bonjour. Je respecte votre décision. Je passais juste dire au revoir proprement — et merci pour tout.",
        "Sans rancune, vraiment. J'ai adoré vivre ici. Si un jour une place se libère, pensez à moi.",
        "C'est la vie ! Je vais très bien. Je voulais simplement vous remercier avant de tourner la page.",
      ],
    }[mood] || [])[vi] || ""),
    exileYes: (mood) => ({ touching: "Oh, merci, merci ! Je ne vous décevrai pas cette fois, promis !", bitter: "…Bon. J'accepte. Mais qu'on ne m'y reprenne plus.", healthy: "Avec joie ! Merci de votre confiance — je reprends ma place le sourire aux lèvres." }[mood] || ""),
    exileNo: (mood) => ({ touching: "Je… je comprends. Prenez soin de la ferme. Adieu.", bitter: "C'est ça. Vous ne perdez rien pour attendre.", healthy: "Pas de souci, je m'y attendais. Portez-vous bien, sincèrement !" }[mood] || ""),
    artisanShopTitle: "🛠️ Ateliers d'artisans",
    artisanBuyBtn: "Construire",
    artisanOwnedBtn: "✅ Construit",
    artisanLockedRow: "🔒 Recrute l'artisan pour débloquer",
    craftSellTitle: "🧺 Produits d'artisans",
    craftRow: (name, n) => `${name} × ${n}`,
    craftPortionBtn: (n) => `Découper une roue → ${n} parts`,
    petFullTitle: "Sac de compagnons plein",
    petFullSub: (petName) => `Un visiteur veut t'offrir ${petName}, mais tu as déjà 2 compagnons. Libère-en un pour l'accueillir, ou refuse le cadeau.`,
    petFullRelease: "Libérer & accepter",
    petFullDecline: "Refuser le cadeau",
    voteDiceChat: (n, r, st) => `🎲 Vote partagé, le dé donne ${r} : ${n} ${st ? "reste !" : "repart..."}`,
    voteLeaveChat: (n) => `${n} repart, le vote n'a pas abouti.`,
    residentTag: (j) => `Habitant(e) : ${j}`,
    notifAsk: (n) => `${n} attend à la mairie`,
    notifWantsBuy: (q, c) => `Veut acheter ${q} × ${c}`,
    notifWantsChat: "Veut juste discuter",
    notifDemand: (g0) => `Exige ${g0} or !`,
    notifStay: "Demande à s'installer !",
    townhall: "Mairie",
    seaSectionHint: "Créature marine rare, se vend cher.",
    seasonSpring: "Printemps",
    seasonSummer: "Été",
    seasonAutumn: "Automne",
    seasonWinter: "Hiver",
    // Écran de code de ferme (hôte)
    codeTitle: "🌾 Ferme Vallée",
    codePrompt: "Entre un code de ferme pour continuer une partie existante, ou un nouveau code pour démarrer une nouvelle ferme. Le même code recharge toujours la même ferme.",
    codePlaceholder: "Code de la ferme (ex: potager)",
    codeLoad: "Ouvrir la ferme",
    codeLoading: "Chargement de la ferme…",
    codeEmpty: "Choisis un code de ferme.",
    codeDbError: "Sauvegarde des fermes indisponible. As-tu exécuté supabase/upgrade-005.sql ?",
    // Sélection de personnage
    csTitle: "🌾 Ferme Vallée",
    csSub: "Ferme coopérative : cultive, coupe, mine et vends avec ton équipe.",
    btnChangeChar: "🧑‍🌾 Changer de perso",
    namePlaceholder: "Ton prénom de fermier·e",
    fermier: "Fermier",
    fermiere: "Fermière",
    joinBtn: "Rejoindre la ferme !",
    connecting: "Connexion à la ferme…",
    waitWorld: "En attente de l'hôte pour ouvrir la ferme…",
    // HUD
    goldCommon: "or (caisse commune)",
    day: "Jour",
    playersOnline: (n) => `${n} joueur(s) en ligne`,
    // Barre d'outils
    seedsLabel: "Graines",
    foodLabel: "Casse-croûte",
    rodLabel: "Canne",
    seedTip: (name) => `${name} (clique pour choisir une autre graine)`,
    toolsTip: (name) => `${name} (touche 1 pour changer d'outil, clique pour choisir)`,
    foodTip: (e) => `Manger (casse-croûte, poisson ou production animale comestible)`,
    rodTip: "Canne à pêche : vise l'eau de la rivière pour pêcher",
    fenceTip: "Clôture : pose ou retire une section sur la case visée (touche R pour choisir son orientation avant de poser)",
    wallTip: "Mur : pose ou retire une section sur la case visée",
    pathTip: "Chemin : pose ou retire une dalle sur la case visée",
    bridgeTip: "Pont : construis une case de pont sur un site de chantier de la rivière (définitif, pas de retrait)",
    bridgeRenovateTip: "Rénover en pierre : améliore une case de pont bois déjà construite (aspect pierre, résiste à la dégradation nocturne)",
    lampTip: "Lampadaire : pose ou retire un lampadaire sur la case visée (chantier de 15 min réelles, puis fonctionnel : éclaire la nuit dans un rayon autour de lui)",
    scarecrowTip: "Épouvantail : pose ou retire un épouvantail sur la case visée (chantier de 10 secondes réelles). Ne bloque pas le passage.",
    // Zip 251 : outil main + décorations.
    handTip: "Main : pose une décoration du sac, déplace lampadaires/épouvantails/décos, ou reprends-les dans le sac (R). Marche à la ferme et en ville.",
    handMenuTitle: "🖐️ Décorations à poser",
    handMenuEmpty: "Aucune décoration en sac. On en reçoit en cadeau des visiteurs.",
    handMoveHint: "Clique un objet pour l'attraper, puis clique une case pour le poser (R = ranger dans le sac).",
    handHeldHint: "Clique une case pour déposer • R pour ranger dans le sac",
    handGrabbed: "Objet attrapé : clique une case pour le poser, ou R pour le ranger.",
    handNothing: "Rien à attraper ici. Arme une décoration ci-dessus pour la poser.",
    decorBadSpot: "Impossible de poser ici.",
    decorNone: "Tu n'as plus cette décoration en sac.",
    decorPicked: "Décoration rangée dans ton sac.",
    objReturned: "Objet rangé dans ton inventaire.",
    handToolName: "Main",
    grassTip: "Herbe : replante de l'herbe sur une case labourée (chantier de 5 secondes réelles, définitif, pas de retrait)",
    millTip: "Moulin : pose un moulin (chantier d'1 heure réelle, transforme le blé déposé en farine en continu, retrait possible seulement à vide)",
    herdTip: "Déplacer : clique un animal pour l'attraper, clique à nouveau pour le déposer où tu veux",
    fenceDirToast: (kind) => `Orientation de la clôture : ${kind === "h" ? "horizontale" : kind === "v" ? "verticale" : "automatique"}`,
    // Ressources (bois/pierre) et menu Construire/Vendre (chantier 2026-07)
    woodResTip: "Bois récolté : clique pour construire ou vendre",
    stoneResTip: "Pierre récoltée : clique pour construire ou vendre",
    gemsResTip: "Gemmes de la salle (partagées entre tous les joueurs) : clique pour vendre",
    flourResTip: "Sacs de farine de la salle (partagés entre tous les joueurs, produits par les moulins) : clique pour vendre",
    craftMenuTitleWood: (n) => `🪵 Bois : ${n}`,
    craftMenuTitleStone: (n) => `🪨 Pierre : ${n}`,
    craftMenuTitleGems: () => `💎 Gemmes partagées`,
    craftMenuTitleFlour: () => `🌾 Farine partagée`,
    flourItemName: "Sac de farine",
    gemsSharedHint: "Partagées entre tous les joueurs de la ferme",
    soanFishSharedHint: "Pêchés par Soan, partagés entre tous les joueurs de la ferme",
    // Zip 260 : Harald, l'agent d'élevage.
    haraldRowTitle: (cost) => `🧺 Engager Harald : ${cost} or`,
    haraldRowSub: "Agent d'élevage — tourne autour de l'enclos et ramasse les productions des animaux (œufs, lait, laine, truffes) pour éviter toute perte.",
    haraldNotHiredSub: "Contrat de 24h",
    haraldHiredUntil: (h) => `Employé — encore ${h}h de contrat`,
    haraldWorkingBtn: "En rondes",
    haraldStatusRounds: "Fait ses rondes autour de l'enclos",
    haraldSharedHint: "Ramassés par Harald, partagés entre tous les joueurs de la ferme",
    employeesHaraldName: "Harald",
    sawmillShopSub: "Atelier du bûcheron",
    buildFenceLabel: "Clôture en bois",
    buildWallLabel: "Mur en pierre",
    buildPathLabel: "Chemin dallé",
    buildCostWood: (n) => `${n} bois la section`,
    buildCostStone: (n) => `${n} pierre la section`,
    buildCostPath: (n) => `${n} pierre la dalle`,
    buildBridgeWoodLabel: "Pont en bois",
    buildBridgeStoneLabel: "Pont en pierre",
    buildBridgeRenovateLabel: "Rénover en pierre",
    buildCostBridgeWood: (n) => `${n} bois la case`,
    buildCostBridgeStone: (n) => `${n} pierre la case`,
    equipBtn: "Équiper",
    // Menu de sélection des graines (clic sur la case graines)
    seedMenuTitle: "Choisir une graine",
    // Menu de sélection d'outil (clic sur la case outils : houe/hache/pioche)
    toolMenuTitle: "Choisir un outil",
    // Pêche / gemmes
    toastNeedWater: "Approche-toi de l'eau et vise la rivière pour pêcher !",
    fxGem: (name) => `Gemme : ${name} !`,
    fxBridge: "Pont !",
    fxLeverOpen: "Pont ouvert !",
    fxLeverClosed: "Pont fermé !",
    fxMillDeposit: (n) => `+${n} blé déposé`,
    fxFish: (name) => `+1 ${name.toLowerCase()}`,
    // Quêtes de découverte
    questTitle: "🎯 À faire : découvre la ferme",
    questBtn: "🎯 À faire",
    questReward: (n) => `+${n} or`,
    questDone: (label, n) => `Quête accomplie : ${label} (+${n} or) !`,
    questAllDone: "🎉 Bravo, tu as fait le tour des bases de la ferme !",
    questLabels: {
      till: "Laboure une case (houe)",
      plant: "Plante une graine",
      water: "Arrose une culture (arrosoir)",
      chop: "Coupe un arbre (hache)",
      mine: "Casse un rocher (pioche)",
      fish: "Pêche un poisson (canne)",
      sell: "Vends quelque chose au bac",
    },
    // Cheval / puits / téléport
    btnWell: "🪣 Puits",
    whistleTip: "Siffler pour rappeler les chevaux",
    mountPrompt: "[F] Monter à cheval",
    dismountPrompt: "[F] Descendre du cheval",
    wellToast: "🪣 Téléport au puits !",
    // Torche / loups (chantier 2026-07)
    torchTipOn: "Éteindre la torche",
    torchTipOff: "Sortir une torche (éloigne les loups)",
    wolfAteAnimal: () => "Un loup a emporté un animal de l'enclos, cette nuit !",
    // Loups agressifs / morsure (chantier 2026-07)
    wolfBiteTitle: "🐺 IL T'ATTAQUE !",
    wolfBiteHint: "Martèle Espace (ou clique) pour le repousser !",
    wolfBiteWin: "Tu as repoussé le loup !",
    wolfBiteFailChat: (who) => `🩸 ${who} a été mordu par un loup et ramené chez lui, blessé.`,
    wolfBiteWinChat: (who) => `🐺 ${who} a repoussé un loup agressif !`,
    // Mise à mort après 3 victoires (chantier 2026-07, demande Guillaume)
    wolfKilledChat: (who) => `🗡️ ${who} a terrassé un loup agressif après trois ripostes !`,
    // Créature maléfique / mini-jeu de morsure (chantier 2026-07)
    evilBiteTitle: "👹 ELLE T'ATTAQUE !",
    evilBiteHint: "Martèle Espace (ou clique) pour lui échapper !",
    evilBiteWin: "Tu as repoussé la créature !",
    evilKilledChat: (who) => `🗡️ ${who} a terrassé une créature maléfique après trois ripostes !`,
    rabbitCaughtChat: (who) => `🐇 ${who} a attrapé un lapin sauvage !`,
    rabbitChallengeOfferTitle: "🐇 Défi chasse aux lapins ?",
    rabbitChallengeOfferSub: (n) => `Au moins 2 fermiers sont en ligne. Lancer un défi : le premier à attraper ${n} lapins gagne un chapeau !`,
    rabbitChallengeActivate: "Activer le défi",
    rabbitChallengeIgnore: "Ignorer",
    rabbitChallengeStarted: (n) => `🐇 Défi lancé : le premier à attraper ${n} lapins gagne un chapeau !`,
    rabbitChallengeWon: (who) => `🎩 ${who} a attrapé 3 lapins et remporte le défi ! Un chapeau lui est offert.`,
    rabbitChallengeProgress: (n, target) => `🐇 Défi lapins : ${n} / ${target}`,
    injuredBanner: (mmss) => `🩸 Blessé — repos forcé (${mmss})`,
    toastInjured: "Tu es blessé, impossible d'agir pour le moment.",
    // Boutique : bâtiments et animaux
    buyLabel: "Acheter",
    shopHorseTitle: (cost) => `🐴 Cheval : ${cost} or`,
    shopHorseSub: "Se déplace bien plus vite une fois enfourché. Approche-toi et appuie sur F (peut porter deux cavaliers).",
    shopHorseCount: (n, max) => `Chevaux dans la ferme : ${n}/${max}`,
    shopHorseMax: "🐴 Nombre maximum de chevaux atteint.",
    shopWellTitle: (cost) => `🪣 Puits : ${cost} or`,
    shopWellSub: "Ajoute un 2e point de téléport dans les champs (bouton 🪣).",
    shopWellOwned: "🪣 Puits déjà construit.",
    shopAnimalsHeader: "🐮 Marché aux animaux",
    // En-têtes de sections de la boutique réorganisée (demande Guillaume 2026-07)
    shopSeedsHeader: "🌱 Graines & cultures",
    shopBuildHeader: "🏗️ Constructions",
    shopConsumablesHeader: "🎒 Consommables & soins",
    shopStaffHeader: "🧑‍🌾 Employés",
    // Maison à niveaux (validation Guillaume 2026-07)
    houseRowTitle: (lvl) => `🏪 FARM MARKET STORE (niveau ${lvl})`, // zip 250 : renommage de la maison centrale (demande Guillaume)
    houseRowSub: "Améliore le FARM MARKET STORE de la ferme (nouveau visuel à chaque niveau). Bois/pierre prélevés sur TON inventaire, or sur la caisse commune.",
    houseRowCost: (pal) => `Passer au niveau ${pal.level} : ${pal.cost.money} or + ${pal.cost.wood} bois + ${pal.cost.stone} pierre. Travaux : ${Math.round(pal.durationMs / 3600000)} h`,
    houseRowMax: "Niveau maximum atteint !",
    houseUpgrading: (mn) => `🔨 Travaux en cours... fin dans ~${mn} min`,
    houseUpgradeBtn: "Lancer les travaux",
    houseWorksStarted: (name, lvl) => `${name} a lancé les travaux du FARM MARKET STORE (vers le niveau ${lvl}) !`,
    houseUpgraded: (lvl) => `🎉 Le FARM MARKET STORE est passé au niveau ${lvl} !`,
    animalRowTitle: (name, cost) => `${name} : ${cost} or`,
    animalRowSub: (prod, sell, hours) => `Produit toutes les ${hours} h : ${prod} (se vend ${sell} or)`,
    penFull: "L'enclos est plein !",
    chatAnimalBought: (name) => `${name} rejoint l'enclos !`,
    promptSellAnimal: (price) => `[E] Vendre l'animal (${price} or)`,
    chatAnimalSold: (name, price) => `💰 ${name} vendu(e) pour ${price} or.`,
    // Bac : productions d'élevage
    prodRowTitle: (name, n) => `${name} × ${n}`,
    fxProduct: (name) => `+1 ${name.toLowerCase()}`,
    fxCollect: "Ramassé !",
    // Minijeu de pêche
    fishBite: (name) => `Ça mord... un ${name.toLowerCase()} !`,
    fishTimingTitle: "🎣 Ferre le poisson !",
    fishTimingHint: "Clique ou Espace quand le curseur est dans la zone verte",
    fishHoldTitle: "🎣 Épuise le poisson !",
    fishHoldHint: "Maintiens (clic ou Espace) pour garder la barre sur le poisson",
    fishReactTitle: "🎣 Prépare-toi...",
    fishReactHint: "Clique DÈS que le cadre devient vert !",
    fishReactNow: "MAINTENANT !",
    fishWin: "Beau poisson !",
    fishFail: "Le poisson s'est échappé...",
    fishTooSoon: "Trop tôt ! Il a filé.",
    // Invites de proximité
    promptShop: "[E] Boutique",
    promptBin: "[E] Vendre",
    promptCoop: "[E] Déposer au chantier",
    promptBarn: "[E] Déposer à la grange",
    promptBarnBuild: "[E] Construire (mini-jeu)",
    promptSleep: "[E] Dormir",
    promptWake: "[E] Se réveiller",
    // Dormir dans la maison (chantier 2026-07)
    toastSleepFull: "Tu n'es pas fatigué, pas besoin de dormir.",
    toastSleepDone: "Bien dormi ! Énergie remplie.",
    toastSleepEarly: "Réveil anticipé.",
    // Trousse de soins (chantier 2026-07) : un autre joueur blessé peut être
    // soigné (touche E à proximité), réduit son repos forcé à 1 minute.
    healKitRowTitle: "🩹 Trousse de soins (gratuite)",
    healKitRowSub: (n) => `Réduit à 1 min le repos forcé d'un coéquipier blessé (approche-toi, touche E). En stock : ${n}`,
    healChat: (healer, hurt) => `🩹 ${healer} a soigné ${hurt}, son repos forcé est réduit à 1 minute !`,
    toastNotInjured: "Ce fermier n'est plus blessé.",
    toastNoHealKit: "Il te faut une trousse de soins (achetable gratuitement au magasin).",
    toastHealTooFar: "Rapproche-toi du fermier blessé pour le soigner.",
    // Grange collaborative persistante (zip 158)
    barnHudLine: (level, max, cap) => `Grange ${level}/${max} · ${cap} animaux max`,
    barnDeposited: (who, n, res) => `${who} apporte ${n} ${res} à la grange.`,
    barnReadyChat: (money) => `🛖 La grange a assez de matériaux, ${money} or ont été prélevés dans la caisse commune : approchez-vous et faites [E] pour construire !`,
    barnBuilt: (who, level) => `🎉 ${who} a fait passer la grange au niveau ${level} !`,
    barnMiniFail: "Raté ! Reviens à la grange pour retenter.",
    barnMiniTitle: (level) => `🔨 Construction de la grange (palier ${level})`,
    barnMiniSub: (hits, needed) => `Coups réussis : ${hits}/${needed}`,
    barnMiniHint: "Clique ou appuie sur Espace quand le curseur est dans la zone verte.",
    toastBarnMax: "La grange est déjà à son niveau maximum.",
    toastFarBarn: "Approche-toi de la grange pour déposer.",
    toastBarnReadyWait: "La grange est prête à être construite : appuie sur E pour lancer le mini-jeu.",
    toastBarnNotReady: "Il manque encore des matériaux avant de pouvoir construire.",
    toastBarnNeedMoney: "Le bois et la pierre sont réunis, mais il manque de l'or dans la caisse commune pour lancer les travaux.",
    // Mission d'équipe (chantier collaboratif, v1)
    coopTitle: "🚧 Mission d'équipe",
    woodLabel: "bois",
    stoneLabel: "pierre",
    coopStarted: (name) => `🚧 Nouvelle mission d'équipe : ${name} ! Apportez du bois et de la pierre au chantier.`,
    coopDeposited: (who, n, res) => `${who} dépose ${n} ${res} au chantier.`,
    coopDone: (name, reward) => `🎉 Mission accomplie : ${name} (+${reward} or) !`,
    toastCoopNone: "Aucune mission d'équipe en cours (revenez à 2 en ligne).",
    toastFarCoop: "Approche-toi du chantier pour déposer.",
    toastCoopNothing: "Tu n'as pas la ressource attendue sur toi (bois ou pierre).",
    // Boutique
    shopTitle: "🛒 Boutique de Pierre",
    shopHint: "Les achats sont payés avec la caisse commune de l'équipe.",
    seedsUsageHint: "Sème une graine sur une case labourée (houe), puis arrose-la (arrosoir équipé : marche dessus, ou vise-la) jusqu'à maturité. L'arrosage reste valable 10h réelles, à renouveler sinon la pousse se met en pause.",
    seedRowSub: (cr) => `Pousse en ${Math.round(cr.growMs / 3600000)} h (arrosée) · se vend ${cr.sell} or · en stock : `,
    seedCostLabel: (cr) => `${cr.seedName} : ${cr.seedCost} or`,
    foodRowTitle: (cost) => `Casse-croûte : ${cost} or`,
    foodRowSub: (e, stock) => `Rend ${e} énergie · en stock : ${stock}`,
    toolsHeader: "⚒ Améliorations d'outils (moins d'énergie, plus efficaces)",
    toolUsage: {
      hoe: "Laboure une case d'herbe pour pouvoir y semer une graine.",
      can: "Arrose une culture plantée pour qu'elle continue de pousser. L'arrosage reste valable 10h réelles, puis il faut réarroser (marcher dessus avec l'arrosoir équipé suffit).",
      axe: "Coupe les arbres pour récolter du bois. Chaque niveau donne aussi ×1,5 plus de bois par arbre.",
      pick: "Casse les rochers pour récolter de la pierre (et parfois une gemme). Chaque niveau donne aussi ×1,5 plus de pierre par rocher.",
    },
    toolRowTitle: (name, lvl) => `${name} : niveau ${lvl}`,
    toolMaxSub: "Niveau maximum atteint !",
    toolUpSub: (lvl, cost) => `Passer au niveau ${lvl} : ${cost} or`,
    buy1: "×1", buy5: "×5", buyOne: "Acheter",
    upgrade: "Améliorer", maxLabel: "MAX",
    fenceRowTitle: (cost) => `Clôture : ${cost} or la section`,
    fenceRowSub: (n) => `Pose ou retire une section où tu veux (touche 8) · en stock : ${n}`,
    lampRowTitle: (cost) => `💡 Lampadaire : ${cost} or`,
    lampRowSub: (n) => `Chantier de 15 min réelles avant d'être fonctionnel, puis éclaire un rayon autour de lui la nuit. Pose ou retire où tu veux (touche 8) · en stock : ${n}`,
    scarecrowRowTitle: (cost) => `🌾 Épouvantail : ${cost} or`,
    scarecrowRowSub: (n) => `Chantier de 10 secondes réelles. Ne bloque pas le passage. Pose ou retire où tu veux (touche 8) · en stock : ${n}`,
    grassRowTitle: (cost) => `🌱 Herbe : ${cost} or l'unité`,
    grassRowSub: (n) => `Replante l'herbe sur une case labourée (chantier de 5 secondes réelles, définitif, pas de retrait) · en stock : ${n}`,
    millRowTitle: (cost) => `🏚️ Moulin : ${cost} or`,
    millRowSub: (n) => `Transforme le blé déposé en sacs de farine, en continu (chantier d'1 heure réelle) · en stock : ${n}`,
    // Bac de vente
    binTitle: "💰 Bac de vente",
    binHint: "L'or gagné va dans la caisse commune de l'équipe.",
    cropRowTitle: (name, n) => `${name} × ${n}`,
    cropRowSub: (cr, n) => `${cr.sell} or pièce · total ${n * cr.sell} or`,
    woodRowTitle: (n) => `Bois × ${n}`,
    stoneRowTitle: (n) => `Pierre × ${n}`,
    sellAll: "Tout vendre",
    // Carte plein écran
    mapTitle: "🗺️ Carte de la vallée",
    mapClose: "Clique n'importe où ou appuie sur Échap ou M pour fermer",
    mapYou: "toi",
    // Boutons flottants
    btnHome: "🏠 Maison",
    btnMap: "🗺️ Carte",
    btnEmployees: "👥 Employés",
    btnChat: "💬 Chat",
    btnLeave: "Quitter",
    homeToast: "🏠 Retour devant la maison !",
    homeBlockedToast: "🌑 Impossible de rentrer d'ici... il faut retrouver le passage.",
    darkPassageToast: "🌑 Une obscurité glaciale t'avale...",
    darkPassageReturnToast: "☀️ Tu retrouves la lumière du jour.",
    evilMonsterCaughtToast: "👹 Une créature t'a happé... tu te réveilles chez toi, blessé.",
    drownToast: "🌊 Glouglou... tu as coulé ! Ramené à la maison, blessé (1 min).",
    mapDarkPassage: "Passage sombre",
    healPartialChat: (soigneur, blesse, mn) => `${soigneur} a appliqué un pansement à ${blesse} : encore ${mn} min de repos (un autre pansement peut aider !)`,
    // Pommade de protection (chantier 2026-07) : achetable au magasin,
    // repousse les créatures maléfiques et immunise le joueur contre elles
    // pendant 10 minutes, pour explorer/farm côté maléfique sans crainte.
    salveRowTitle: "🧴 Pommade de protection",
    salveRowSub: (n) => `Utilisée : repousse les créatures maléfiques et t'immunise contre elles pendant 10 min. Se fabrique au chaudron (⚗️). En stock : ${n}`,
    salveUseLabel: "Utiliser",
    salveUsedToast: "🧴 Pommade appliquée : immunisé contre les créatures maléfiques pendant 10 minutes.",
    toastNoSalve: "Il te faut une pommade de protection (à fabriquer au chaudron).",
    immunityBanner: (t) => `🧴 Invisible et immunisé aux créatures maléfiques — ${t}`,
    // Chaudron de la pommade de protection (chantier 2026-07) : recette
    // coopérative (1 améthyste + 2 truites + 1 brochet), voir CAULDRON_SITE/
    // SALVE_RECIPE (fermeConstants.js) et resolveSalveDeposit/resolveSalveBrew
    // (fermeEngine.js).
    promptCauldron: "[E] Chaudron (concocter)",
    promptCauldronIgnite: "[E] Allumer le chaudron 🔥",
    promptCauldronBrewing: (s) => `⏳ Concoction en cours... ${s}s`,
    promptCauldronCollect: "[E] Récupérer la pommade",
    promptSalveDeposit: "[E] Déposer poisson au chaudron",
    promptSalveBrew: "[E] Lancer la concoction",
    salveDeposited: (who, n, res) => `${who} dépose ${n} ${res} au chaudron.`,
    salveIgnited: (who) => `🔥 ${who} allume le feu sous le chaudron ! Concoction en cours (1 min)...`,
    salveBrewed: (who) => `⚗️ ${who} récupère une pommade de protection au chaudron !`,
    toastFarCauldron: "Approche-toi du chaudron pour déposer ou concocter.",
    toastNoFishToDeposit: "Tu ne portes ni truite ni brochet à déposer.",
    toastCauldronMissing: "Il manque des ingrédients (1 améthyste, 2 truites, 1 brochet), ou le chaudron n'est pas encore posé.",
    toastCauldronBrewing: "⏳ La concoction est déjà en cours, reviens dans un instant.",
    toastCauldronNothingToCollect: "Rien à récupérer au chaudron pour l'instant.",
    toastCauldronNeedTorch: "Allume d'abord ta torche pour lancer le feu sous le chaudron !",
    toastCauldronHasEnough: "Le chaudron a déjà tout le poisson nécessaire pour cette recette.",
    cauldronNeedAmethyst: "Il manque une améthyste dans la réserve commune de gemmes pour lancer la recette.",
    troutLabel: "truite(s)",
    pikeLabel: "brochet(s)",
    // Menu du chaudron (chantier 2026-07, refonte demande Guillaume : "une
    // fois la recette sélectionnée, le chaudron doit proposer de déposer les
    // ingrédients ? Oui-Non [...] si tous les ingrédients sont là alors on
    // peut cliquer sur prêt ! et puis le chaudron indiquera allumez le
    // chaudron") : liste de produits (une seule entrée pour l'instant),
    // confirmation avant chaque dépôt, bouton "Prêt !" une fois la recette
    // complète, puis allumage effectif dans le monde (clic/E sur le
    // chaudron, torche en main) — voir cauldronPlaceIngredients/
    // igniteCauldron/tryOpenNearby, FermeGame.js.
    cauldronMenuTitle: "⚗️ Que voulez-vous concocter ?",
    cauldronMenuHint: "Réunis les ingrédients du parchemin, puis va allumer ta torche et clique sur le chaudron pour lancer le feu.",
    cauldronProductSalveName: "🧴 Pommade magique",
    // Parchemin de recette (demande Guillaume 2026-07) : nom en haut, liste
    // des ingrédients (avec avancement), effet en bas dans une formulation
    // voilée, sans chiffres de gameplay.
    scrollIngAmethyst: (have, need) => `${need} améthyste de la réserve commune (${have}/${need})`,
    scrollIngTrout: (dep, need) => `${need} truites versées au chaudron (${dep}/${need})`,
    scrollIngPike: (dep, need) => `${need} brochet versé au chaudron (${dep}/${need})`,
    cauldronScrollEffect: "« Qui s'en oint la peau chemine un temps parmi les ombres, et les créatures de la nuit se détournent de son passage. »",
    cauldronAddBtn: "🫗 Ajouter les ingrédients",
    cauldronReadyBtn: "✅ Prêt !",
    cauldronReadyHint: "Recette complète — va allumer ta torche puis clique sur le chaudron pour lancer la concoction !",
    cauldronIgniteHint: "Torche en main, clique sur le chaudron pour allumer le feu et lancer la concoction (1 min).",
    // Chaudron ramené du monde maléfique (chantier 2026-07, demande
    // Guillaume) : artéfact ramassable UNE SEULE fois côté maléfique, puis
    // posable où on veut côté ferme avec l'outil Construction (voir
    // O_CAULDRON/EVIL_CAULDRON_SPAWN, fermeConstants.js).
    promptEvilCauldronPickup: "[E] Ramasser le chaudron",
    evilCauldronPickedToast: "⚗️ Tu as récupéré le chaudron ! Ramène-le côté ferme et pose-le où tu veux (outil Construction).",
    toastCauldronAlreadyTaken: "Ce chaudron a déjà été récupéré.",
    toastNoCauldronStock: "Tu ne portes pas de chaudron à poser.",
    toastCauldronNotEmpty: "Vide le chaudron (poisson déposé) avant de le déplacer.",
    cauldronRowTitle: "⚗️ Chaudron",
    cauldronRowSub: "Ramené du monde maléfique. Pose-le où tu veux avec l'outil Construction : il sert alors à fabriquer la pommade de protection.",
    // Aide
    help1: "ZQSD/WASD/Flèches : bouger (8 directions) · Espace/Clic : utiliser l'outil",
    help2: "1-8 : outils (7 = canne, 8 = clôture) · E : boutique/vente · T : chat · M : carte · 🏠 : maison",
    // Toasts
    toastTired: "Trop de fatigue ! Mange un casse-croûte ou attends demain.",
    toastFarShop: "Approche-toi de la boutique !",
    toastFarBin: "Approche-toi du bac de vente !",
    toastNoGold: "Pas assez d'or !",
    toastToolMax: "Outil au niveau maximum !",
    toastNoFence: "Plus de section de clôture, achètes-en à la boutique !",
    toastNoWood: "Pas assez de bois !",
    toastNoStone: "Pas assez de pierre !",
    toastNoWallStock: "Plus de mur en stock, fabrique-en avec de la pierre !",
    toastNoPathStock: "Plus de dalle en stock, fabrique-en avec de la pierre !",
    toastNoLampStock: "Plus de lampadaire en stock, achètes-en à la boutique !",
    toastNoScarecrowStock: "Plus d'épouvantail en stock, achètes-en à la boutique !",
    toastNoGrassStock: "Plus d'herbe en stock, achètes-en à la boutique !",
    toastNoMillStock: "Plus de moulin en stock, achètes-en un à la boutique !",
    toastMillNotEmpty: "Vide d'abord le moulin (il reste du blé à transformer) avant de le retirer.",
    toastNoWheatToDeposit: "Tu n'as pas de blé récolté à déposer.",
    toastMillFull: "Le moulin est plein de blé, attends qu'il en transforme avant d'en redéposer.",
    toastActionFailed: "Action impossible, réessaie.",
    toastNewDay: (day) => `☀ Jour ${day} ! Énergie restaurée.`,
    // Chat système
    chatWelcome: "Bienvenue sur la ferme ! Appuie sur T pour discuter avec ton équipe.",
    chatToolUp: (name, lvl) => `${name} au niveau ${lvl} !`,
    chatSell: (gain, total) => `Vente : +${gain} or ! Caisse commune : ${total} or`,
    chatNewDay: (day) => `Jour ${day}, bonne journée à la ferme !`,
    chatStormyDay: "Le ciel se couvre... orage et pluie toute la journée, prends un imperméable !",
    chatJoin: (name) => `${name} rejoint la ferme.`,
    chatLeave: (name) => `${name} a quitté la ferme.`,
    // Effets flottants
    fxWood: (n) => `+${n} bois`,
    fxStone: (n) => `+${n} pierre`,
    fxMagicOre: (n) => `+${n} minerai magique`,
    fxHarvest: (name) => `+1 ${name.toLowerCase()}`,
    fxGold: (n) => `+${n} or`,
    fxEat: "Miam !",
    chatSend: "Message… (Entrée pour envoyer)",
    hireLabel: "Engager",
    gregRowTitle: (cost) => `🧑‍🌾 Engager Greg : ${cost} or`,
    gregRowSub: "Employé de champs — arrose tout automatiquement toutes les 10h, et exécute tes ordres de labour/plantation.",
    gregNotHiredSub: "Contrat de 2 jours",
    gregHiredUntil: (h) => `Employé — encore ${h}h de contrat`,
    gregOrderBtn: "Donner un ordre",
    gregOrderTitle: "Ordonner à Greg de labourer, planter puis arroser",
    gregOrderCountLabel: "Nombre de cases",
    gregOrderCost: (n) => `Coût : ${n} or`,
    gregOrderHint: "Greg labourera intelligemment autour de l'endroit où tu te trouveras quand tu lanceras l'ordre.",
    gregOrderArmBtn: "Choisir cet ordre",
    gregOrderFab: "📍 Lancer Greg ici",
    gregOrderCancel: "Annuler l'ordre",
    toastGregNotHired: "Greg n'est pas (ou plus) engagé !",
    toastGregNoRoom: "Greg ne trouve plus de place libre pour ça !",
    toastGregNoFertilizer: "Plus d'engrais en stock !",
    soanRowTitle: (cost) => `🎣 Engager Soan : ${cost} or`,
    soanRowSub: "Employé pêcheur — pêche à la rivière sur ton ordre, peut y rester toute la journée.",
    soanNotHiredSub: "Contrat de 24h",
    soanHiredUntil: (h) => `Employé — encore ${h}h de contrat`,
    soanOrderBtn: "Envoyer pêcher",
    soanRecallBtn: "Rappeler",
    soanStatusRoam: "Se balade, en attente d'ordre",
    soanStatusToRiver: "En route vers la rivière",
    soanStatusFishing: "Pêche à la rivière",
    soanStatusBreak: "En pause, il se balade",
    toastSoanNotHired: "Soan n'est pas (ou plus) engagé !",
    toastSoanNoRiver: "Soan ne trouve pas de rivière accessible !",
    // Menu "Employés actifs" (chantier 2026-07, demande Guillaume) : liste
    // les employés sous contrat, avec accès direct à leurs ordres.
    employeesTitle: "👥 Employés actifs",
    employeesHint: "Les employés sous contrat en ce moment, avec un accès direct pour leur donner un ordre.",
    employeesGregName: "Greg",
    employeesSoanName: "Soan",
    fertilizerShopLabel: "Engrais",
    fertilizerShopBuy: (cost) => `Acheter (${cost} or)`,
    fertilizerShopStock: (n) => `Stock : ${n}`,
    fertilizerOrderBtn: "Épandre de l'engrais",
    fertilizerOrderTitle: "Ordonner à Greg d'épandre de l'engrais",
    fertilizerOrderCost: "Coût : 1 engrais (zone 5x5)",
    fertilizerOrderHint: "Greg accélère la pousse de toutes les cultures déjà plantées dans un carré de 5x5 cases autour de l'endroit où tu te trouveras quand tu lanceras l'ordre.",
    fertilizerOrderArmBtn: "Choisir cet ordre",
    fertilizerOrderAvailable: (n) => `Engrais disponible : ${n}`,
    // --- Zip 235 ---
    berryLabel: "Baies",
    fruitLabel: "Pommes",
    perPiece: (p) => `${p} or / pièce`,
    toastBerriesPicked: (n) => `🫐 +${n} baie(s)`,
    toastFruitPicked: (n) => `🍎 +${n} pomme(s)`,
    toastFruitCooldown: "L'arbre a déjà été cueilli aujourd'hui.",
    passageWorldToast: (name) => `🌀 Cette semaine, le passage mène à : ${name}.`,
    passageLootToast: (gold) => `✨ +${gold} or !`,
    passagePetToast: (name) => `🐾 Vous avez apprivoisé un(e) ${name} !`,
    mazePrizeToast: (gold) => `🏆 Prix du labyrinthe : +${gold} or !`,
    candySpeedToast: "🍬 Bonbon vitesse : +50 % pendant 1 min !",
    sleepInHouseToast: "🛏️ Bonne nuit à Valley Town.",
    townHouseStyleChangeBtn: (n) => `Style de façade : ${n} / 10 (R pour changer)`,
    meetAtHallBtn: "Rejoindre à la mairie",
    seasonRotate: (name) => `🌦️ Nouvelle saison : ${name}.`,
    // --- Zip 236 : sac personnel ---
    bagBtn: "Sac",
    bagTitle: "Mon sac",
    bagPetsTitle: (n, max) => `Compagnons (${n} / ${max})`,
    bagNoPets: "Aucun compagnon pour l'instant. Attrape-en un dans le passage sombre !",
    bagDecorTitle: "Décorations",
    bagNoDecor: "Aucune décoration. Les visiteurs en offrent après un deal.",
    bagDecorHint: "Équipe l'outil main (8) pour les poser à la ferme ou en ville.",
    bagReleaseBtn: "Relâcher",
    bagReleasedToast: (name) => `👋 ${name} retourne à la vie sauvage.`,
    bagPetsFull: (max) => `Sac plein (${max} compagnons). Relâches-en un pour en attraper un autre.`,
    bagHealTitle: "Soins",
    bagSalveRow: (n) => `Baume d'immunité × ${n}`,
    bagSalveSub: "À utiliser avant d'entrer dans le passage sombre.",
    bagHealKitRow: (n) => `Pansements × ${n}`,
    bagHealKitSub: "Pour soigner un autre joueur blessé.",
    bagEnergyTitle: "Énergie",
    bagEnergyRow: (e, max) => `${e} / ${max}`,
    bagSleepHint: "Dors chez toi (ferme ou Valley Town, touche E) pour recharger sans acheter de snacks.",
    petCaughtToast: (name) => `🐾 ${name} rejoint ton sac !`,
    // --- Zip 237 : troc + pets communs ---
    giftUseful: (n, item) => `${n} ${item}`,
    swapTitle: (name) => `${name} propose un troc`,
    swapWantLabel: "Il/elle veut :",
    swapGiveLabel: "En échange :",
    swapAcceptBtn: "Troquer",
    swapNotEnough: "Tu n'as pas assez de marchandise pour ce troc.",
    swapDone: (name, give) => `Troc conclu avec ${name} : tu reçois ${give} !`,
    notifSwap: "propose un troc",
    swapPocket: (have, n) => `${have} / ${n} en poche`,
  },
  en: {
    // --- 2026-07 station update (sea creatures, ducks, station, visitors, seasons) ---
    seaCaught: (n) => `Rare catch: ${n}!`,
    seaBite: (n) => `Something unusual bites... ${n}?!`,
    stationName: "Village station",
    promptStation: "E: station ad board",
    adsTitle: "🚉 Ad board",
    adsIntro: "Post what the farm sells to attract visitors by train. Each new ad costs a posting fee (common chest). No prices are listed: visitors surprise us with their offers.",
    adsFee: (c) => `Fee: ${c} gold per new ad`,
    adsSave: "Post the ads",
    adsSaved: (c) => c > 0 ? `Ads posted (${c} gold in fees).` : "Ads updated.",
    adCatCrops: "🌾 Crops & vegetables",
    adCatAnimal: "🥚 Farm products",
    adCatFish: "🐟 Fish & fishing",
    adCatResources: "🪵 Wood & stone",
    adsBlacklistTitle: "🚫 Blacklist",
    adsBlacklistEmpty: "Nobody is banned yet.",
    adsBlacklistHint: "A banned visitor will never ride the train here again.",
    visitorArrived: (n) => `🚂 ${n} is arriving by train!`,
    visitorsArrived: (ns) => `🚂 Visitors are arriving by train: ${ns}!`,
    visitorLeftChat: (n) => `${n} heads back to the station.`,
    promptVisitor: (n) => `Q: talk to ${n}`,
    visitorPanelTitle: (n) => `🧳 ${n}`,
    visitorWantsBuy: (n, q, c, p) => `${n} wants to buy ${q} × ${c} and offers ${p} gold each.`,
    visitorRichBonus: (b) => `Plus a ${b} gold bonus if the deal is done!`,
    visitorWantsChat: (n) => `${n} just came to see the farm and chat.`,
    visitorDemand: (n, g0) => `${n} demands ${g0} gold from the chest, or our crops and gold will pay the price!`,
    visitorUrgent: "URGENT",
    visitorAccept: "Close the deal",
    visitorChatBtn: "Chat",
    visitorPayBtn: (g0) => `Pay ${g0} gold`,
    visitorRefuseBtn: "Refuse",
    visitorBlacklistBtn: "Blacklist this visitor",
    visitorNotEnough: "You don't carry enough of that crop.",
    visitorDealDone: (n, g0) => `Deal closed with ${n}: +${g0} gold to the chest!`,
    visitorChatDone: (n) => `${n} enjoyed the chat. (friendship +1)`,
    visitorPaid: (n, g0) => `${n} pockets ${g0} gold and leaves. What a character...`,
    visitorRelation: (r) => `Friendship: ${r}`,
    visitorStock: (h, n) => `You carry ${h} / ${n} asked.`,
    visitorEasyNote: "Easy order: already in stock, modest price.",
    visitorPrepNote: "An order to prepare: takes longer, pays better.",
    visitorRewardGift: (g) => `On top of the gold, ${g} if the deal is done!`,
    visitorGiftGranted: (n, g) => `🎁 ${n} leaves a gift: ${g}!`,
    visitorGiftQueued: (n, g) => `🎁 ${n} promises a gift: ${g}. It will be delivered as soon as possible!`,
    visitorGiftPromised: (n, g) => `🎁 ${n} promises to send you a gift: ${g}. It will arrive in a few minutes!`, // zip 250
    visitorGiftDelivered: (n, g) => `🎁 The gift promised by ${n} just landed in your bag: ${g}!`, // zip 250
    giftSeed: (s) => `unique seeds (${s})`,
    giftDecor: (d) => `a unique decoration (${d})`,
    giftPet: (pt) => `a pet (${pt})`,
    meetBtn: "Meet me at townhall",
    notifMore: (n) => `+${n} more visitor(s) waiting`,
    visitorChatSaid: (n, l0) => `${n}: ${l0}`,
    visitorChatLines: [
      [
        "Lovely day for a stroll, isn't it?",
        "The train was packed today — your farm is getting famous!",
        "It smells like fresh soil around here. I like it.",
        "Just passing through, but this place is charming.",
      ],
      [
        "Good to see you again! I think about this farm often.",
        "I told the whole train car about your harvests. They were jealous.",
        "You always make my visits worth the ride.",
        "The townhall square is my favourite spot in the valley.",
      ],
      [
        "Between friends, no need to haggle for long!",
        "I always keep room in my bags for you... and sometimes a present.",
        "This farm feels like a second home to me now.",
        "If you ever come by Valley Town, my door is open.",
      ],
    ],
    visitorThanks: (n) => `${n} thanks you and strolls around the square a while longer.`,
    visitorHomeChat: (n) => `${n} heads back to the station, happy with the visit.`,
    visitorArrivalGift: (n, g) => `🎁 ${n} came bearing a gift: ${g}!`,
    visitorTotal: (t) => `${t} gold in total`,
    visitorPerUnit: (p) => `${p} gold / unit`,
    visitorPocket: "In your pocket",
    visitorCloseBtn: "Not now",
    visitorChatTitle: "Chat",
    promptTrainRide: "E: ride the train to Valley Town",
    promptTrainBack: "E: ride the train back to the farm",
    trainToTownToast: "🚆 Welcome to Valley Town!",
    trainToFarmToast: "🚆 Back at the farm.",
    promptTownHouse: (n) => `${n}'s house`,
    promptTownHouseSale: "House for sale",
    toastYourHouse: "This is your Valley Town house. Interiors are coming soon!",
    toastTheirHouse: (n) => `This is ${n}'s house.`,
    toastHouseSale: "This house is waiting for a new farmer.",
    townSaleSign: "For sale",
    cropTipReady: "ready!",
    cropTipWater: "needs water",
    adsGiftsTitle: "🎁 Promised gifts",
    adsGiftsEmpty: "No gift pending.",
    adsGiftRow: (g, n) => `${g} (promised by ${n})`,
    hostileDamageChat: (n, g0, cr) => `⚠️ ${n} struck: ${g0} gold stolen, ${cr} crop(s) ruined! Gather up to repair!`,
    repairTitle: "🛠️ Repair the damage",
    repairIntro: (n) => `${n} wrecked the farm! Click when the cursor is in the green zone. Every player who succeeds brings full repair closer.`,
    repairHits: (h, t) => `Hits: ${h} / ${t}`,
    repairWin: "Well done! Your share of the repair is complete.",
    repairFail: "Missed... try again while the window is still open.",
    repairProgress: (w0, n0) => `Repair: ${w0} / ${n0} player(s). Almost there!`,
    repairDoneChat: (g0, cr) => `✅ Damage repaired together: ${g0} gold recovered, ${cr} crop(s) replanted!`,
    repairExpired: "The repair window has closed... the damage is permanent.",
    stayTitle: (n) => `🏠 ${n} wants to move in!`,
    stayProposal: (n, j) => `${n} proposes to live on the farm and contribute: "${j}". The vote must be unanimous. On a split vote, a dice roll decides.`,
    voteYes: "✅ For",
    voteNo: "❌ Against",
    voteWaiting: "Vote recorded, waiting for the other players...",
    voteStayChat: (n) => `🎉 Unanimous vote: ${n} is moving in!`,
    residentStarted: (n, job) => `${n} moves into one of the houses for sale and gets to work: ${job}.`,
    // Zip 252: artisans / workshops / products.
    residentMovedIn: (n, job) => `🏡 ${n} moved onto the farm and will ${job}.`,
    residentNoRoom: "No free house left to take in a resident.",
    artisanNoResident: "You first need the matching artisan living with you.",
    artisanBuilt: (b) => `🔨 ${b} built! The artisan can start producing.`,
    buildingName: (bid) => ({ beehive: "Beehive", fromagerie: "Cheese dairy", bakery: "Bakery", sawmill: "Sawmill" }[bid] || bid),
    craftName: (item) => ({ honey: "Honey jar", cheeseWheel: "Cheese wheel", cheesePortion: "Cheese portion", pastry: "Pastry" }[item] || item),
    craftSold: (name, n, gain) => `Sold: ${n} × ${name} (+${gain} gold)! Common pot topped up.`,
    cheeseCut: (w, p) => `🧀 Cut ${w} wheel(s) into ${p} portions.`,
    promptResident: (n) => `Q — talk to ${n}`,
    recruitAsk: "Ask to move in",
    residentGreet: (n, job) => `Hi! I'm ${n}. My trade is: ${job}.`,
    // Zip 262: skilled visitors introduce their trade explicitly.
    skillLabel: (sk) => ({ beekeeper: "beekeeper", cheesemaker: "cheesemaker", baker: "baker", lumberjack: "lumberjack", voyager: "traveling merchant" }[sk] || sk),
    skillPitch: (sk, n) => ({
      beekeeper: `Hi! I'm ${n}, I'm a beekeeper and I'd like to help you keep bees and jar honey.`,
      cheesemaker: `Hi! I'm ${n}, I'm a cheesemaker and I'd like to help you turn your milk into fine cheese.`,
      baker: `Hi! I'm ${n}, I'm a baker and I'd like to help you bake pastries and cakes.`,
      lumberjack: `Hi! I'm ${n}, I'm a lumberjack and I'd like to help you fell trees and break rocks.`,
      voyager: `Hi! I'm ${n}, I'm a traveling merchant and I'd like to sail the world to bring you rare goods.`,
    }[sk] || `Hi! I'm ${n}.`),
    residentNeedBuilding: (b) => `Build me a ${b} (buyable with gold at the shop) and I'll produce for the farm!`,
    residentBuildingReady: (b) => `My ${b} is running. Keep our stocks filled and I'll do the rest!`,
    residentLumberjackLine: "I fell trees and break rocks all day — it all goes into our common stock.",
    residentCloseBtn: "See you later",
    // Zip 253: enriched resident card + Staff tab.
    residentRoleTitle: "Output",
    residentNotWorkingYet: "No workshop yet — still settling in.",
    residentProdHoney: (n) => `Hive humming — ${n} honey jar(s) in store.`,
    residentProdCheese: (w, p) => `Dairy running — ${w} wheel(s), ${p} portion(s) aging.`,
    residentProdPastry: (n) => `Oven's on — ${n} pastry(ies) ready.`,
    residentProdWood: (w, s) => `Common stock: ${w} wood, ${s} stone brought in.`,
    residentSeeBtn: "View",
    // Zip 258: baker out-of-ingredients alert.
    bakeryAlertShort: "⚠️ Out of ingredients",
    bakeryAlertLine: "⚠️ Oven stopped — I'm out of ingredients!",
    bakeryAlertTitle: "The baker needs ingredients",
    bakeryAlertMsg: "I can't carry on: each batch needs 1 milk, 1 flour and 6 eggs. Top up our stocks and I'll get right back to it!",
    bakeryAlertToast: "🍰 The baker is out of ingredients — production stopped.",
    bakeryNotifSee: "View",
    // Zip 258: Eduardo Da Fonseca, the great-voyager trader.
    voyagerStatusHome: "Back in the village — ready to set sail again.",
    voyagerStatusAway: (d) => `Away on a voyage — back in ~${d}.`,
    voyagerOrderBtn: "Order a voyage",
    voyagerSellBtn: "Resell the goods",
    voyagerOrderTitle: "🌍 Order a voyage from Eduardo",
    voyagerOrderHint: "Pick the world goods to bring back. The farther the region, the pricier the goods and the longer the trip. Paid up front.",
    voyagerTripDays: (d) => `${d} day(s) of travel`,
    voyagerUnitCost: (c) => `${c} gold/unit`,
    voyagerTotal: (c) => `Total: ${c} gold`,
    voyagerSendBtn: "Send Eduardo",
    voyagerCancelBtn: "Cancel",
    voyagerEmptyOrder: "Add at least one product.",
    voyagerDeparted: (d) => `🐎 Eduardo sets off (back in ${d}). Fair winds!`,
    voyagerBusyToast: "Eduardo is already away on a voyage.",
    voyagerReturned: (goods) => `🧳 Eduardo is back with: ${goods}!`,
    voyagerReturnNotifTitle: "Eduardo is back!",
    voyagerSurpriseTag: " (+ surprise)",
    voyagerSellTitle: "🌍 World goods to resell",
    voyagerSellRow: (name, n) => `${name} × ${n}`,
    worldGoodName: (key) => ({ vanilla: "Vanilla pod", coffee: "Coffee", cinnamon: "Cinnamon", cocoa: "Cocoa", pineapple: "Pineapple", coconut: "Coconut" }[key] || key),
    voyagerProdLine: (n) => n > 0 ? `Voyager's counter — ${n} world good(s) in store.` : "Great-voyager trader — ready to depart.",
    // Zip 259: evict a resident + returning ex-resident.
    residentsSectionTitle: "Residents",
    kickBtn: "Vote to evict",
    kickTally: (n, m) => `Eviction: ${n}/${m} votes`,
    kickedChat: (name) => `👋 ${name} has been evicted and vacates their house.`,
    kickVotedToast: "Your eviction vote is recorded.",
    exileReturnChat: (name) => `${name} is back in the village and wants a word…`,
    pleaTitle: (name) => `${name} is back`,
    pleaAccept: "Take them back",
    pleaRefuse: "Refuse",
    notifPlea: "wants a word",
    exileReacceptedChat: (name) => `🏡 ${name} moves back in — good to see them again!`,
    exileRefusedChat: (name) => `${name} leaves for good.`,
    exilePlea: (mood, vi) => (({
      touching: [
        "…I don't understand. I was so happy with you. Could I come back? I'll do better, I promise.",
        "I missed you every single day. This farm was my family. Please, give me a second chance.",
        "I haven't slept since I left. Tell me what I did wrong and I'll fix it — just take me back.",
        "I walked for hours to come back. My heart stayed here, with you. Let me come home…",
      ],
      bitter: [
        "So you toss people out like worn-out tools? You'll regret this, believe me.",
        "I'm back, but not to beg. You were unfair, and you know it perfectly well.",
        "I gave everything to this farm, and this is how you thank me. Pathetic.",
        "Don't think I'll forget. You always reap what you sow.",
      ],
      healthy: [
        "Hello. I respect your decision. I just came to say a proper goodbye — and thank you for everything.",
        "No hard feelings, truly. I loved living here. If a spot ever opens up, think of me.",
        "That's life! I'm doing great. I only wanted to thank you before turning the page.",
      ],
    }[mood] || [])[vi] || ""),
    exileYes: (mood) => ({ touching: "Oh, thank you, thank you! I won't let you down this time, I promise!", bitter: "…Fine. I accept. But don't you do that to me again.", healthy: "Gladly! Thank you for your trust — I'll take my place back with a smile." }[mood] || ""),
    exileNo: (mood) => ({ touching: "I… I understand. Take care of the farm. Farewell.", bitter: "Right. You'll get what's coming to you.", healthy: "No worries, I expected as much. Take care, truly!" }[mood] || ""),
    artisanShopTitle: "🛠️ Artisan workshops",
    artisanBuyBtn: "Build",
    artisanOwnedBtn: "✅ Built",
    artisanLockedRow: "🔒 Recruit the artisan to unlock",
    craftSellTitle: "🧺 Artisan goods",
    craftRow: (name, n) => `${name} × ${n}`,
    craftPortionBtn: (n) => `Cut a wheel → ${n} portions`,
    petFullTitle: "Companion bag full",
    petFullSub: (petName) => `A visitor wants to give you ${petName}, but you already have 2 companions. Release one to take it in, or decline the gift.`,
    petFullRelease: "Release & accept",
    petFullDecline: "Decline the gift",
    voteDiceChat: (n, r, st) => `🎲 Split vote, the die shows ${r}: ${n} ${st ? "stays!" : "leaves..."}`,
    voteLeaveChat: (n) => `${n} leaves, the vote did not pass.`,
    residentTag: (j) => `Resident: ${j}`,
    notifAsk: (n) => `${n} is waiting at the townhall`,
    notifWantsBuy: (q, c) => `Wants to buy ${q} × ${c}`,
    notifWantsChat: "Just wants to chat",
    notifDemand: (g0) => `Demands ${g0} gold!`,
    notifStay: "Asks to move in!",
    townhall: "Townhall",
    seaSectionHint: "Rare sea creature, sells high.",
    seasonSpring: "Spring",
    seasonSummer: "Summer",
    seasonAutumn: "Autumn",
    seasonWinter: "Winter",
    codeTitle: "🌾 Valley Farm",
    codePrompt: "Enter a farm code to continue an existing game, or a new code to start a new farm. The same code always reloads the same farm.",
    codePlaceholder: "Farm code (e.g. garden)",
    codeLoad: "Open the farm",
    codeLoading: "Loading the farm…",
    codeEmpty: "Choose a farm code.",
    codeDbError: "Farm saves unavailable. Did you run supabase/upgrade-005.sql?",
    csTitle: "🌾 Valley Farm",
    csSub: "Co-op farm: grow, chop, mine and sell with your team.",
    btnChangeChar: "🧑‍🌾 Change character",
    namePlaceholder: "Your farmer name",
    fermier: "Farmer (M)",
    fermiere: "Farmer (F)",
    joinBtn: "Join the farm!",
    connecting: "Connecting to the farm…",
    waitWorld: "Waiting for the host to open the farm…",
    goldCommon: "gold (shared pot)",
    day: "Day",
    playersOnline: (n) => `${n} player(s) online`,
    seedsLabel: "Seeds",
    foodLabel: "Snack",
    rodLabel: "Rod",
    seedTip: (name) => `${name} (click to pick another seed)`,
    toolsTip: (name) => `${name} (press 1 to switch tool, click to choose)`,
    foodTip: (e) => `Eat (snack, fish, or an edible animal product)`,
    rodTip: "Fishing rod: aim at the river water to fish",
    fenceTip: "Fence: place or remove a section on the targeted tile (press R to pick its orientation before placing)",
    wallTip: "Wall: place or remove a section on the targeted tile",
    pathTip: "Path: place or remove a tile on the targeted tile",
    bridgeTip: "Bridge: build a bridge tile on a river construction site (permanent, cannot be removed)",
    bridgeRenovateTip: "Renovate to stone: upgrades an already-built wooden bridge tile (stone look, resists nightly decay)",
    lampTip: "Lamp post: place or remove a lamp post on the targeted tile (15 real min to build, then functional: lights up an area at night)",
    scarecrowTip: "Scarecrow: place or remove a scarecrow on the targeted tile (10 real seconds to build). Does not block movement.",
    // Zip 251: hand tool + decorations.
    handTip: "Hand: place a decoration from your bag, move lamps/scarecrows/decorations, or store them back in your bag (R). Works on the farm and in town.",
    handMenuTitle: "🖐️ Decorations to place",
    handMenuEmpty: "No decorations in your bag. You get them as gifts from visitors.",
    handMoveHint: "Click an object to grab it, then click a tile to drop it (R = store in bag).",
    handHeldHint: "Click a tile to drop • R to store in your bag",
    handGrabbed: "Object grabbed: click a tile to drop it, or R to store it.",
    handNothing: "Nothing to grab here. Arm a decoration above to place it.",
    decorBadSpot: "Can't place here.",
    decorNone: "You no longer have that decoration in your bag.",
    decorPicked: "Decoration stored in your bag.",
    objReturned: "Object stored in your inventory.",
    handToolName: "Hand",
    grassTip: "Grass: replant grass on a tilled tile (5 real seconds to build, permanent, cannot be removed)",
    millTip: "Mill: places a mill (1 real hour to build, continuously turns deposited wheat into flour, can only be removed once empty)",
    herdTip: "Move: click an animal to pick it up, click again to drop it wherever you want",
    fenceDirToast: (kind) => `Fence orientation: ${kind === "h" ? "horizontal" : kind === "v" ? "vertical" : "automatic"}`,
    woodResTip: "Harvested wood: click to build or sell",
    stoneResTip: "Harvested stone: click to build or sell",
    gemsResTip: "Room gems (shared between all players): click to sell",
    flourResTip: "Room flour sacks (shared between all players, produced by mills): click to sell",
    craftMenuTitleWood: (n) => `🪵 Wood: ${n}`,
    craftMenuTitleStone: (n) => `🪨 Stone: ${n}`,
    craftMenuTitleGems: () => `💎 Shared gems`,
    craftMenuTitleFlour: () => `🌾 Shared flour`,
    flourItemName: "Flour sack",
    gemsSharedHint: "Shared between all players on the farm",
    soanFishSharedHint: "Caught by Soan, shared between all players on the farm",
    // Zip 260: Harald, the livestock agent.
    haraldRowTitle: (cost) => `🧺 Hire Harald: ${cost} gold`,
    haraldRowSub: "Livestock agent — roams the pen and collects animal produce (eggs, milk, wool, truffles) so nothing is wasted.",
    haraldNotHiredSub: "24h contract",
    haraldHiredUntil: (h) => `Hired — ${h}h left on contract`,
    haraldWorkingBtn: "On rounds",
    haraldStatusRounds: "Doing rounds around the pen",
    haraldSharedHint: "Collected by Harald, shared between all players on the farm",
    employeesHaraldName: "Harald",
    sawmillShopSub: "Lumberjack's workshop",
    buildFenceLabel: "Wooden fence",
    buildWallLabel: "Stone wall",
    buildPathLabel: "Paved path",
    buildCostWood: (n) => `${n} wood per section`,
    buildCostStone: (n) => `${n} stone per section`,
    buildCostPath: (n) => `${n} stone per tile`,
    buildBridgeWoodLabel: "Wooden bridge",
    buildBridgeStoneLabel: "Stone bridge",
    buildBridgeRenovateLabel: "Renovate to stone",
    buildCostBridgeWood: (n) => `${n} wood per tile`,
    buildCostBridgeStone: (n) => `${n} stone per tile`,
    equipBtn: "Equip",
    seedMenuTitle: "Choose a seed",
    toolMenuTitle: "Choose a tool",
    toastNeedWater: "Get close to the water and aim at the river to fish!",
    fxGem: (name) => `Gem: ${name}!`,
    fxBridge: "Bridge!",
    fxLeverOpen: "Bridge open!",
    fxLeverClosed: "Bridge closed!",
    fxMillDeposit: (n) => `+${n} wheat deposited`,
    fxFish: (name) => `+1 ${name.toLowerCase()}`,
    questTitle: "🎯 To do: discover the farm",
    questBtn: "🎯 To do",
    questReward: (n) => `+${n} gold`,
    questDone: (label, n) => `Quest done: ${label} (+${n} gold)!`,
    questAllDone: "🎉 Well done, you've covered the farm basics!",
    questLabels: {
      till: "Till a tile (hoe)",
      plant: "Plant a seed",
      water: "Water a crop (watering can)",
      chop: "Chop a tree (axe)",
      mine: "Break a rock (pickaxe)",
      fish: "Catch a fish (rod)",
      sell: "Sell something at the bin",
    },
    btnWell: "🪣 Well",
    whistleTip: "Whistle to call the horses back",
    mountPrompt: "[F] Mount the horse",
    dismountPrompt: "[F] Dismount",
    wellToast: "🪣 Teleported to the well!",
    torchTipOn: "Put out the torch",
    torchTipOff: "Take out a torch (scares wolves away)",
    wolfAteAnimal: () => "A wolf carried off a pen animal tonight!",
    // Aggressive wolves / bite (chantier 2026-07)
    wolfBiteTitle: "🐺 IT'S ATTACKING YOU!",
    wolfBiteHint: "Mash Space (or click) to fight it off!",
    wolfBiteWin: "You fought off the wolf!",
    wolfBiteFailChat: (who) => `🩸 ${who} was bitten by a wolf and dragged back home, injured.`,
    wolfBiteWinChat: (who) => `🐺 ${who} fought off an aggressive wolf!`,
    // Kill after 3 wins (chantier 2026-07, Guillaume's request)
    wolfKilledChat: (who) => `🗡️ ${who} slew an aggressive wolf after three fend-offs!`,
    // Evil creature / bite minigame (chantier 2026-07)
    evilBiteTitle: "👹 IT'S ATTACKING YOU!",
    evilBiteHint: "Mash Space (or click) to break free!",
    evilBiteWin: "You fought off the creature!",
    evilKilledChat: (who) => `🗡️ ${who} slew an evil creature after three fend-offs!`,
    rabbitCaughtChat: (who) => `🐇 ${who} caught a wild rabbit!`,
    rabbitChallengeOfferTitle: "🐇 Rabbit-catching challenge?",
    rabbitChallengeOfferSub: (n) => `At least 2 farmers are online. Start a challenge: first to catch ${n} rabbits wins a hat!`,
    rabbitChallengeActivate: "Start the challenge",
    rabbitChallengeIgnore: "Ignore",
    rabbitChallengeStarted: (n) => `🐇 Challenge started: first to catch ${n} rabbits wins a hat!`,
    rabbitChallengeWon: (who) => `🎩 ${who} caught 3 rabbits and won the challenge! A hat has been awarded.`,
    rabbitChallengeProgress: (n, target) => `🐇 Rabbit challenge: ${n} / ${target}`,
    injuredBanner: (mmss) => `🩸 Injured — forced rest (${mmss})`,
    toastInjured: "You're injured and can't act right now.",
    buyLabel: "Buy",
    shopHorseTitle: (cost) => `🐴 Horse: ${cost} gold`,
    shopHorseSub: "Moves much faster once mounted. Walk up to it and press F (can carry two riders).",
    shopHorseCount: (n, max) => `Horses on the farm: ${n}/${max}`,
    shopHorseMax: "🐴 Maximum number of horses reached.",
    shopWellTitle: (cost) => `🪣 Well: ${cost} gold`,
    shopWellSub: "Adds a 2nd teleport point in the fields (🪣 button).",
    shopWellOwned: "🪣 Well already built.",
    shopAnimalsHeader: "🐮 Animal market",
    // Section headers of the reorganized shop (Guillaume's request 2026-07)
    shopSeedsHeader: "🌱 Seeds & crops",
    shopBuildHeader: "🏗️ Buildings",
    shopConsumablesHeader: "🎒 Consumables & care",
    shopStaffHeader: "🧑‍🌾 Employees",
    // House levels (Guillaume's validation 2026-07)
    houseRowTitle: (lvl) => `🏪 FARM MARKET STORE (level ${lvl})`, // zip 250: central house renamed (Guillaume)
    houseRowSub: "Upgrades the farm FARM MARKET STORE (new look at each level). Wood/stone taken from YOUR inventory, gold from the shared pot.",
    houseRowCost: (pal) => `Reach level ${pal.level}: ${pal.cost.money} gold + ${pal.cost.wood} wood + ${pal.cost.stone} stone — works: ${Math.round(pal.durationMs / 3600000)} h`,
    houseRowMax: "Maximum level reached!",
    houseUpgrading: (mn) => `🔨 Works in progress — done in ~${mn} min`,
    houseUpgradeBtn: "Start the works",
    houseWorksStarted: (name, lvl) => `${name} started the FARM MARKET STORE works (towards level ${lvl})!`,
    houseUpgraded: (lvl) => `🎉 The FARM MARKET STORE reached level ${lvl}!`,
    animalRowTitle: (name, cost) => `${name}: ${cost} gold`,
    animalRowSub: (prod, sell, hours) => `Produces every ${hours} h: ${prod} (sells for ${sell} gold)`,
    penFull: "The pen is full!",
    chatAnimalBought: (name) => `${name} joins the pen!`,
    promptSellAnimal: (price) => `[E] Sell the animal (${price} gold)`,
    chatAnimalSold: (name, price) => `💰 ${name} sold for ${price} gold.`,
    prodRowTitle: (name, n) => `${name} × ${n}`,
    fxProduct: (name) => `+1 ${name.toLowerCase()}`,
    fxCollect: "Collected!",
    fishBite: (name) => `A bite... a ${name.toLowerCase()}!`,
    fishTimingTitle: "🎣 Hook the fish!",
    fishTimingHint: "Click or Space when the cursor is in the green zone",
    fishHoldTitle: "🎣 Tire the fish out!",
    fishHoldHint: "Hold (click or Space) to keep the bar on the fish",
    fishReactTitle: "🎣 Get ready...",
    fishReactHint: "Click AS SOON AS the frame turns green!",
    fishReactNow: "NOW!",
    fishWin: "Nice catch!",
    fishFail: "The fish got away...",
    fishTooSoon: "Too soon! It escaped.",
    promptShop: "[E] Shop",
    promptBin: "[E] Sell",
    promptCoop: "[E] Deposit at site",
    promptBarn: "[E] Deposit at barn",
    promptBarnBuild: "[E] Build (mini-game)",
    promptSleep: "[E] Sleep",
    promptWake: "[E] Wake up",
    // Sleeping in the house (2026-07 chantier)
    toastSleepFull: "You're not tired, no need to sleep.",
    toastSleepDone: "Slept well! Energy refilled.",
    toastSleepEarly: "Woke up early.",
    // Heal kit (2026-07 chantier): another injured player can be healed
    // (press E nearby), cutting their forced rest down to 1 minute.
    healKitRowTitle: "🩹 Heal kit (free)",
    healKitRowSub: (n) => `Cuts an injured teammate's forced rest to 1 min (walk up to them, press E). In stock: ${n}`,
    healChat: (healer, hurt) => `🩹 ${healer} healed ${hurt}, forced rest cut down to 1 minute!`,
    toastNotInjured: "That farmer isn't injured anymore.",
    toastNoHealKit: "You need a heal kit (free at the shop).",
    toastHealTooFar: "Get closer to the injured farmer to heal them.",
    // Persistent collaborative barn (zip 158)
    barnHudLine: (level, max, cap) => `Barn ${level}/${max} · ${cap} animals max`,
    barnDeposited: (who, n, res) => `${who} brings ${n} ${res} to the barn.`,
    barnReadyChat: (money) => `🛖 The barn has enough materials, ${money} gold was taken from the shared pot: come over and press [E] to build!`,
    barnBuilt: (who, level) => `🎉 ${who} upgraded the barn to level ${level}!`,
    barnMiniFail: "Missed it! Come back to the barn to try again.",
    barnMiniTitle: (level) => `🔨 Building the barn (tier ${level})`,
    barnMiniSub: (hits, needed) => `Successful hits: ${hits}/${needed}`,
    barnMiniHint: "Click or press Space when the cursor is in the green zone.",
    toastBarnMax: "The barn is already at its maximum level.",
    toastFarBarn: "Get closer to the barn to deposit.",
    toastBarnReadyWait: "The barn is ready to be built: press E to start the mini-game.",
    toastBarnNotReady: "Still missing some materials before you can build.",
    toastBarnNeedMoney: "Wood and stone are ready, but the shared pot doesn't have enough gold to start the work.",
    // Team mission (collaborative construction site, v1)
    coopTitle: "🚧 Team mission",
    woodLabel: "wood",
    stoneLabel: "stone",
    coopStarted: (name) => `🚧 New team mission: ${name}! Bring wood and stone to the site.`,
    coopDeposited: (who, n, res) => `${who} drops ${n} ${res} at the site.`,
    coopDone: (name, reward) => `🎉 Mission complete: ${name} (+${reward} gold)!`,
    toastCoopNone: "No team mission running right now (come back with 2+ online).",
    toastFarCoop: "Get closer to the site to deposit.",
    toastCoopNothing: "You're not carrying the needed resource (wood or stone).",
    shopTitle: "🛒 Pierre's Shop",
    shopHint: "Purchases are paid from the team's shared pot.",
    seedsUsageHint: "Plant a seed on a tilled tile (hoe), then water it (equip the watering can: walk over it, or aim at it) until it's mature. Watering stays valid for 10 real hours; renew it or growth pauses.",
    seedRowSub: (cr) => `Grows in ${Math.round(cr.growMs / 3600000)} h (watered) · sells for ${cr.sell} gold · in stock: `,
    seedCostLabel: (cr) => `${cr.seedNameEn} : ${cr.seedCost} gold`,
    foodRowTitle: (cost) => `Snack: ${cost} gold`,
    foodRowSub: (e, stock) => `Restores ${e} energy · in stock: ${stock}`,
    toolsHeader: "⚒ Tool upgrades (less energy, more efficient)",
    toolUsage: {
      hoe: "Tills a grass tile so you can plant a seed on it.",
      can: "Waters a planted crop so it keeps growing. Watering stays valid for 10 real hours, then it needs renewing (walking over it with the can equipped is enough).",
      axe: "Chops trees to harvest wood. Each level also gives ×1.5 more wood per tree.",
      pick: "Breaks rocks to harvest stone (and sometimes a gem). Each level also gives ×1.5 more stone per rock.",
    },
    toolRowTitle: (name, lvl) => `${name}: level ${lvl}`,
    toolMaxSub: "Maximum level reached!",
    toolUpSub: (lvl, cost) => `Upgrade to level ${lvl}: ${cost} gold`,
    buy1: "×1", buy5: "×5", buyOne: "Buy",
    upgrade: "Upgrade", maxLabel: "MAX",
    fenceRowTitle: (cost) => `Fence: ${cost} gold per section`,
    fenceRowSub: (n) => `Place or remove a section anywhere (key 8) · in stock: ${n}`,
    lampRowTitle: (cost) => `💡 Lamp post: ${cost} gold`,
    lampRowSub: (n) => `15 real min to build before it's functional, then lights up an area around it at night. Place or remove anywhere (key 8) · in stock: ${n}`,
    scarecrowRowTitle: (cost) => `🌾 Scarecrow: ${cost} gold`,
    scarecrowRowSub: (n) => `10 real seconds to build. Does not block movement. Place or remove anywhere (key 8) · in stock: ${n}`,
    grassRowTitle: (cost) => `🌱 Grass: ${cost} gold per unit`,
    grassRowSub: (n) => `Replant grass on a tilled tile (5 real seconds to build, permanent, cannot be removed) · in stock: ${n}`,
    millRowTitle: (cost) => `🏚️ Mill: ${cost} gold`,
    millRowSub: (n) => `Continuously turns deposited wheat into flour sacks (1 real hour to build) · in stock: ${n}`,
    binTitle: "💰 Sell bin",
    binHint: "Gold earned goes into the team's shared pot.",
    cropRowTitle: (name, n) => `${name} × ${n}`,
    cropRowSub: (cr, n) => `${cr.sell} gold each · total ${n * cr.sell} gold`,
    woodRowTitle: (n) => `Wood × ${n}`,
    stoneRowTitle: (n) => `Stone × ${n}`,
    sellAll: "Sell all",
    mapTitle: "🗺️ Valley map",
    mapClose: "Click anywhere or press Esc or M to close",
    mapYou: "you",
    btnHome: "🏠 House",
    btnMap: "🗺️ Map",
    btnEmployees: "👥 Staff",
    btnChat: "💬 Chat",
    btnLeave: "Leave",
    homeToast: "🏠 Back to the house!",
    homeBlockedToast: "🌑 Can't teleport home from here... find the passage back.",
    darkPassageToast: "🌑 A cold darkness swallows you...",
    darkPassageReturnToast: "☀️ You find daylight again.",
    evilMonsterCaughtToast: "👹 A creature caught you... you wake up at home, injured.",
    drownToast: "🌊 Glub glub... you sank! Carried back home, injured (1 min).",
    mapDarkPassage: "Dark passage",
    healPartialChat: (healer, hurt, mn) => `${healer} applied a bandage to ${hurt}: ${mn} min of rest left (another bandage can help!)`,
    // Protection salve (2026-07 chantier): buyable at the shop, repels evil
    // creatures and makes the player immune to them for 10 minutes, so they
    // can explore/farm the evil side without worry.
    salveRowTitle: "🧴 Protection salve",
    salveRowSub: (n) => `When used: repels evil creatures and grants immunity to them for 10 min. Crafted at the cauldron (⚗️). In stock: ${n}`,
    salveUseLabel: "Use",
    salveUsedToast: "🧴 Salve applied: immune to evil creatures for 10 minutes.",
    toastNoSalve: "You need a protection salve (craft it at the cauldron).",
    immunityBanner: (t) => `🧴 Invisible and immune to evil creatures — ${t}`,
    // Protection salve cauldron (2026-07 chantier): cooperative recipe (1
    // amethyst + 2 trout + 1 pike).
    promptCauldron: "[E] Cauldron (brew)",
    promptCauldronIgnite: "[E] Light the cauldron 🔥",
    promptCauldronBrewing: (s) => `⏳ Brewing in progress... ${s}s`,
    promptCauldronCollect: "[E] Collect the salve",
    promptSalveDeposit: "[E] Deposit fish at the cauldron",
    promptSalveBrew: "[E] Start brewing",
    salveDeposited: (who, n, res) => `${who} deposits ${n} ${res} at the cauldron.`,
    salveIgnited: (who) => `🔥 ${who} lights the fire under the cauldron! Brewing in progress (1 min)...`,
    salveBrewed: (who) => `⚗️ ${who} collects a protection salve at the cauldron!`,
    toastFarCauldron: "Get closer to the cauldron to deposit or brew.",
    toastCauldronBrewing: "⏳ Already brewing, come back in a moment.",
    toastCauldronNothingToCollect: "Nothing to collect at the cauldron right now.",
    toastCauldronNeedTorch: "Light your torch first to start the fire under the cauldron!",
    toastCauldronHasEnough: "The cauldron already has all the fish it needs for this recipe.",
    cauldronNeedAmethyst: "The common gem reserve is missing an amethyst to start this recipe.",
    // Cauldron menu (2026-07 chantier, revamp): "deposit ingredients? Yes/No"
    // (becomes "Complete" once the team already started), then a "Ready!"
    // button once the recipe is complete — actually lighting the fire now
    // happens in the world (click/E on the cauldron, torch in hand), not
    // from a menu button. See cauldronPlaceIngredients/igniteCauldron/
    // tryOpenNearby, FermeGame.js.
    cauldronMenuTitle: "⚗️ What would you like to brew?",
    cauldronMenuHint: "Gather the ingredients on the scroll, then go light your torch and click the cauldron to start the fire.",
    cauldronProductSalveName: "🧴 Magic salve",
    scrollIngAmethyst: (have, need) => `${need} amethyst from the common reserve (${have}/${need})`,
    scrollIngTrout: (dep, need) => `${need} trout poured into the cauldron (${dep}/${need})`,
    scrollIngPike: (dep, need) => `${need} pike poured into the cauldron (${dep}/${need})`,
    cauldronScrollEffect: "“Who anoints their skin with it walks a while among the shadows, and the creatures of the night turn away from their path.”",
    cauldronAddBtn: "🫗 Add the ingredients",
    cauldronReadyBtn: "✅ Ready!",
    cauldronReadyHint: "Recipe complete — go light your torch, then click the cauldron to start brewing!",
    cauldronIgniteHint: "Torch in hand, click the cauldron to light the fire and start brewing (1 min).",
    promptEvilCauldronPickup: "[E] Pick up the cauldron",
    evilCauldronPickedToast: "⚗️ You picked up the cauldron! Bring it back to the farm and place it anywhere (Build tool).",
    toastCauldronAlreadyTaken: "This cauldron has already been picked up.",
    toastNoCauldronStock: "You aren't carrying a cauldron to place.",
    toastCauldronNotEmpty: "Empty the cauldron (deposited fish) before moving it.",
    cauldronRowTitle: "⚗️ Cauldron",
    cauldronRowSub: "Brought back from the evil world. Place it anywhere with the Build tool: it's then used to craft the protection salve.",
    toastNoFishToDeposit: "You're not carrying any trout or pike to deposit.",
    toastCauldronMissing: "Missing ingredients (1 amethyst, 2 trout, 1 pike), or the cauldron isn't placed yet.",
    troutLabel: "trout",
    pikeLabel: "pike",
    help1: "WASD/Arrows: move (8 directions) · Space/Click: use tool",
    help2: "1-8: tools (7 = rod, 8 = fence) · E: shop/sell · T: chat · M: map · 🏠: house",
    toastTired: "Too tired! Eat a snack or wait for tomorrow.",
    toastFarShop: "Get closer to the shop!",
    toastFarBin: "Get closer to the sell bin!",
    toastNoGold: "Not enough gold!",
    toastToolMax: "Tool already at max level!",
    toastNoFence: "Out of fence sections, buy more at the shop!",
    toastNoWood: "Not enough wood!",
    toastNoStone: "Not enough stone!",
    toastNoWallStock: "Out of wall sections, craft more from stone!",
    toastNoPathStock: "Out of path tiles, craft more from stone!",
    toastNoLampStock: "Out of lamp posts, buy more at the shop!",
    toastNoScarecrowStock: "Out of scarecrows, buy more at the shop!",
    toastNoGrassStock: "Out of grass, buy more at the shop!",
    toastNoMillStock: "Out of mills, buy one at the shop!",
    toastMillNotEmpty: "Empty the mill first (it still has wheat to grind) before removing it.",
    toastNoWheatToDeposit: "You don't have any harvested wheat to deposit.",
    toastMillFull: "The mill is full of wheat, wait for it to grind some before depositing more.",
    toastActionFailed: "Couldn't do that, try again.",
    toastNewDay: (day) => `☀ Day ${day}! Energy restored.`,
    chatWelcome: "Welcome to the farm! Press T to chat with your team.",
    chatToolUp: (name, lvl) => `${name} upgraded to level ${lvl}!`,
    chatSell: (gain, total) => `Sale: +${gain} gold! Shared pot: ${total} gold`,
    chatNewDay: (day) => `Day ${day}, have a great day on the farm!`,
    chatStormyDay: "The sky is turning grey... storm and rain all day, grab a raincoat!",
    chatJoin: (name) => `${name} joined the farm.`,
    chatLeave: (name) => `${name} left the farm.`,
    fxWood: (n) => `+${n} wood`,
    fxStone: (n) => `+${n} stone`,
    fxMagicOre: (n) => `+${n} magic ore`,
    fxHarvest: (name) => `+1 ${name.toLowerCase()}`,
    fxGold: (n) => `+${n} gold`,
    fxEat: "Yum!",
    chatSend: "Message… (Enter to send)",
    hireLabel: "Hire",
    gregRowTitle: (cost) => `🧑‍🌾 Hire Greg: ${cost} gold`,
    gregRowSub: "Field worker — auto-waters everything every 10h, and carries out your till/plant orders.",
    gregNotHiredSub: "2-day contract",
    gregHiredUntil: (h) => `Hired — ${h}h left on contract`,
    gregOrderBtn: "Give an order",
    gregOrderTitle: "Order Greg to till, plant then water",
    gregOrderCountLabel: "Number of tiles",
    gregOrderCost: (n) => `Cost: ${n} gold`,
    gregOrderHint: "Greg will till smartly around wherever you're standing when you launch the order.",
    gregOrderArmBtn: "Choose this order",
    gregOrderFab: "📍 Send Greg here",
    gregOrderCancel: "Cancel order",
    toastGregNotHired: "Greg isn't hired (anymore)!",
    toastGregNoRoom: "Greg can't find free space for that!",
    toastGregNoFertilizer: "No fertilizer left in stock!",
    soanRowTitle: (cost) => `🎣 Hire Soan: ${cost} gold`,
    soanRowSub: "Fisher — fishes at the river on your order, can stay there all day.",
    soanNotHiredSub: "24h contract",
    soanHiredUntil: (h) => `Hired — ${h}h left on contract`,
    soanOrderBtn: "Send fishing",
    soanRecallBtn: "Recall",
    soanStatusRoam: "Wandering, waiting for orders",
    soanStatusToRiver: "Heading to the river",
    soanStatusFishing: "Fishing at the river",
    soanStatusBreak: "On break, taking a walk",
    toastSoanNotHired: "Soan isn't hired (anymore)!",
    toastSoanNoRiver: "Soan can't find a reachable river!",
    employeesTitle: "👥 Active staff",
    employeesHint: "Employees currently under contract, with direct access to give them an order.",
    employeesGregName: "Greg",
    employeesSoanName: "Soan",
    fertilizerShopLabel: "Fertilizer",
    fertilizerShopBuy: (cost) => `Buy (${cost} gold)`,
    fertilizerShopStock: (n) => `Stock: ${n}`,
    fertilizerOrderBtn: "Spread fertilizer",
    fertilizerOrderTitle: "Order Greg to spread fertilizer",
    fertilizerOrderCost: "Cost: 1 fertilizer (5x5 area)",
    fertilizerOrderHint: "Greg will speed up the growth of every already-planted crop in a 5x5 square around wherever you're standing when you launch the order.",
    fertilizerOrderArmBtn: "Choose this order",
    fertilizerOrderAvailable: (n) => `Fertilizer available: ${n}`,
    // --- Zip 235 ---
    berryLabel: "Berries",
    fruitLabel: "Apples",
    perPiece: (p) => `${p} gold / each`,
    toastBerriesPicked: (n) => `🫐 +${n} berrie(s)`,
    toastFruitPicked: (n) => `🍎 +${n} apple(s)`,
    toastFruitCooldown: "This tree has already been picked today.",
    passageWorldToast: (name) => `🌀 This week the passage leads to: ${name}.`,
    passageLootToast: (gold) => `✨ +${gold} gold!`,
    passagePetToast: (name) => `🐾 You tamed a ${name}!`,
    mazePrizeToast: (gold) => `🏆 Maze prize: +${gold} gold!`,
    candySpeedToast: "🍬 Speed candy: +50% for 1 min!",
    sleepInHouseToast: "🛏️ Sleep well in Valley Town.",
    townHouseStyleChangeBtn: (n) => `Facade style: ${n} / 10 (R to change)`,
    meetAtHallBtn: "Meet at townhall",
    seasonRotate: (name) => `🌦️ New season: ${name}.`,
    // --- Zip 236: personal bag ---
    bagBtn: "Bag",
    bagTitle: "My bag",
    bagPetsTitle: (n, max) => `Companions (${n} / ${max})`,
    bagNoPets: "No companions yet. Catch one in the dark passage!",
    bagDecorTitle: "Decorations",
    bagNoDecor: "No decorations yet. Visitors gift them after a deal.",
    bagDecorHint: "Equip the hand tool (8) to place them on the farm or in town.",
    bagReleaseBtn: "Release",
    bagReleasedToast: (name) => `👋 ${name} returns to the wild.`,
    bagPetsFull: (max) => `Bag full (${max} companions). Release one to catch another.`,
    bagHealTitle: "Healing",
    bagSalveRow: (n) => `Immunity salve × ${n}`,
    bagSalveSub: "Use it before entering the dark passage.",
    bagHealKitRow: (n) => `Bandaids × ${n}`,
    bagHealKitSub: "Heal another injured player.",
    bagEnergyTitle: "Energy",
    bagEnergyRow: (e, max) => `${e} / ${max}`,
    bagSleepHint: "Sleep at home (farm or Valley Town, press E) to recharge without buying snacks.",
    petCaughtToast: (name) => `🐾 ${name} joins your bag!`,
    // --- Zip 237: barter + common pets ---
    giftUseful: (n, item) => `${n} ${item}`,
    swapTitle: (name) => `${name} offers a trade`,
    swapWantLabel: "They want:",
    swapGiveLabel: "In return:",
    swapAcceptBtn: "Trade",
    swapNotEnough: "You don't have enough goods for this trade.",
    swapDone: (name, give) => `Trade done with ${name}: you get ${give}!`,
    notifSwap: "offers a trade",
    swapPocket: (have, n) => `${have} / ${n} in pocket`,
  },
};

export function fstr(lang) {
  return FERME_STR[lang === "en" ? "en" : "fr"];
}
