/* ==========================================================================
   FERME VALLÉE (jeu 22) — libellés bilingues INTERNES au jeu.
   ==========================================================================
   Le jeu est très riche en texte (boutique, bac, aides, toasts). Pour ne pas
   gonfler lib/i18n.js (STR) de plusieurs dizaines de clés et risquer une
   asymétrie FR/EN, ces libellés propres au jeu vivent ici, en un dictionnaire
   { fr, en } auto-porté. Seuls le NOM et le TAG de la carte (nameFerme /
   tagFerme) sont dans lib/i18n.js, car page.js en a besoin hors du composant.

   Règle site : AUCUN tiret quadratin dans le texte FR joueur.
   `fstr(lang)` renvoie le bon jeu de libellés ; les fonctions acceptent des
   paramètres (niveau d'outil, gain, etc.).
   ========================================================================== */

export const FERME_STR = {
  fr: {
    // Écran de code de ferme (hôte)
    codeTitle: "🌾 Ferme Vallée",
    codePrompt: "Entre un code de ferme pour continuer une partie existante, ou un nouveau code pour démarrer une nouvelle ferme. Le même code recharge toujours la même ferme.",
    codePlaceholder: "Code de la ferme (ex: potager)",
    codeLoad: "Ouvrir la ferme",
    codeLoading: "Chargement de la ferme…",
    codeEmpty: "Choisis un code de ferme.",
    codeDbError: "Sauvegarde des fermes indisponible. As-tu exécuté supabase/upgrade-005.sql ?",
    // Sélection de personnage
    csTitle: "🌾 Ferme Vallée",
    csSub: "Ferme coopérative : cultive, coupe, mine et vends avec ton équipe.",
    btnChangeChar: "🧑‍🌾 Changer de perso",
    namePlaceholder: "Ton prénom de fermier·e",
    fermier: "Fermier",
    fermiere: "Fermière",
    joinBtn: "Rejoindre la ferme !",
    connecting: "Connexion à la ferme…",
    waitWorld: "En attente de l'hôte pour ouvrir la ferme…",
    // HUD
    goldCommon: "or (caisse commune)",
    day: "Jour",
    playersOnline: (n) => `${n} joueur(s) en ligne`,
    // Barre d'outils
    seedsLabel: "Graines",
    foodLabel: "Casse-croûte",
    rodLabel: "Canne",
    seedTip: (name) => `${name} (clique pour choisir une autre graine)`,
    toolsTip: (name) => `${name} (touche 1 pour changer d'outil, clique pour choisir)`,
    foodTip: (e) => `Manger (casse-croûte, poisson ou production animale comestible)`,
    rodTip: "Canne à pêche : vise l'eau de la rivière pour pêcher",
    fenceTip: "Clôture : pose ou retire une section sur la case visée (touche R pour choisir son orientation avant de poser)",
    wallTip: "Mur : pose ou retire une section sur la case visée",
    pathTip: "Chemin : pose ou retire une dalle sur la case visée",
    bridgeTip: "Pont : construis une case de pont sur un site de chantier de la rivière (définitif, pas de retrait)",
    bridgeRenovateTip: "Rénover en pierre : améliore une case de pont bois déjà construite (aspect pierre, résiste à la dégradation nocturne)",
    lampTip: "Lampadaire : pose ou retire un lampadaire sur la case visée (chantier de 15 min réelles, puis fonctionnel : éclaire la nuit dans un rayon autour de lui)",
    scarecrowTip: "Épouvantail : pose ou retire un épouvantail sur la case visée (chantier de 10 secondes réelles). Ne bloque pas le passage.",
    grassTip: "Herbe : replante de l'herbe sur une case labourée (chantier de 5 secondes réelles, définitif, pas de retrait)",
    millTip: "Moulin : pose un moulin (chantier d'1 heure réelle, transforme le blé déposé en farine en continu, retrait possible seulement à vide)",
    herdTip: "Déplacer : clique un animal pour l'attraper, clique à nouveau pour le déposer où tu veux",
    fenceDirToast: (kind) => `Orientation de la clôture : ${kind === "h" ? "horizontale" : kind === "v" ? "verticale" : "automatique"}`,
    // Ressources (bois/pierre) et menu Construire/Vendre (chantier 2026-07)
    woodResTip: "Bois récolté : clique pour construire ou vendre",
    stoneResTip: "Pierre récoltée : clique pour construire ou vendre",
    gemsResTip: "Gemmes de la salle (partagées entre tous les joueurs) : clique pour vendre",
    flourResTip: "Sacs de farine de la salle (partagés entre tous les joueurs, produits par les moulins) : clique pour vendre",
    craftMenuTitleWood: (n) => `🪵 Bois : ${n}`,
    craftMenuTitleStone: (n) => `🪨 Pierre : ${n}`,
    craftMenuTitleGems: () => `💎 Gemmes partagées`,
    craftMenuTitleFlour: () => `🌾 Farine partagée`,
    flourItemName: "Sac de farine",
    gemsSharedHint: "Partagées entre tous les joueurs de la ferme",
    soanFishSharedHint: "Pêchés par Soan, partagés entre tous les joueurs de la ferme",
    buildFenceLabel: "Clôture en bois",
    buildWallLabel: "Mur en pierre",
    buildPathLabel: "Chemin dallé",
    buildCostWood: (n) => `${n} bois la section`,
    buildCostStone: (n) => `${n} pierre la section`,
    buildCostPath: (n) => `${n} pierre la dalle`,
    buildBridgeWoodLabel: "Pont en bois",
    buildBridgeStoneLabel: "Pont en pierre",
    buildBridgeRenovateLabel: "Rénover en pierre",
    buildCostBridgeWood: (n) => `${n} bois la case`,
    buildCostBridgeStone: (n) => `${n} pierre la case`,
    equipBtn: "Équiper",
    // Menu de sélection des graines (clic sur la case graines)
    seedMenuTitle: "Choisir une graine",
    // Menu de sélection d'outil (clic sur la case outils : houe/hache/pioche)
    toolMenuTitle: "Choisir un outil",
    // Pêche / gemmes
    toastNeedWater: "Approche-toi de l'eau et vise la rivière pour pêcher !",
    fxGem: (name) => `Gemme : ${name} !`,
    fxBridge: "Pont !",
    fxLeverOpen: "Pont ouvert !",
    fxLeverClosed: "Pont fermé !",
    fxMillDeposit: (n) => `+${n} blé déposé`,
    fxFish: (name) => `+1 ${name.toLowerCase()}`,
    // Quêtes de découverte
    questTitle: "🎯 À faire : découvre la ferme",
    questBtn: "🎯 À faire",
    questReward: (n) => `+${n} or`,
    questDone: (label, n) => `Quête accomplie : ${label} (+${n} or) !`,
    questAllDone: "🎉 Bravo, tu as fait le tour des bases de la ferme !",
    questLabels: {
      till: "Laboure une case (houe)",
      plant: "Plante une graine",
      water: "Arrose une culture (arrosoir)",
      chop: "Coupe un arbre (hache)",
      mine: "Casse un rocher (pioche)",
      fish: "Pêche un poisson (canne)",
      sell: "Vends quelque chose au bac",
    },
    // Cheval / puits / téléport
    btnWell: "🪣 Puits",
    whistleTip: "Siffler pour rappeler les chevaux",
    mountPrompt: "[F] Monter à cheval",
    dismountPrompt: "[F] Descendre du cheval",
    wellToast: "🪣 Téléport au puits !",
    // Torche / loups (chantier 2026-07)
    torchTipOn: "Éteindre la torche",
    torchTipOff: "Sortir une torche (éloigne les loups)",
    wolfAteAnimal: () => "Un loup a emporté un animal de l'enclos, cette nuit !",
    // Loups agressifs / morsure (chantier 2026-07)
    wolfBiteTitle: "🐺 IL T'ATTAQUE !",
    wolfBiteHint: "Martèle Espace (ou clique) pour le repousser !",
    wolfBiteWin: "Tu as repoussé le loup !",
    wolfBiteFailChat: (who) => `🩸 ${who} a été mordu par un loup et ramené chez lui, blessé.`,
    wolfBiteWinChat: (who) => `🐺 ${who} a repoussé un loup agressif !`,
    // Créature maléfique / mini-jeu de morsure (chantier 2026-07)
    evilBiteTitle: "👹 ELLE T'ATTAQUE !",
    evilBiteHint: "Martèle Espace (ou clique) pour lui échapper !",
    evilBiteWin: "Tu as repoussé la créature !",
    rabbitCaughtChat: (who) => `🐇 ${who} a attrapé un lapin sauvage !`,
    rabbitChallengeOfferTitle: "🐇 Défi chasse aux lapins ?",
    rabbitChallengeOfferSub: (n) => `Au moins 2 fermiers sont en ligne. Lancer un défi : le premier à attraper ${n} lapins gagne un chapeau !`,
    rabbitChallengeActivate: "Activer le défi",
    rabbitChallengeIgnore: "Ignorer",
    rabbitChallengeStarted: (n) => `🐇 Défi lancé : le premier à attraper ${n} lapins gagne un chapeau !`,
    rabbitChallengeWon: (who) => `🎩 ${who} a attrapé 3 lapins et remporte le défi ! Un chapeau lui est offert.`,
    rabbitChallengeProgress: (n, target) => `🐇 Défi lapins : ${n} / ${target}`,
    injuredBanner: (mmss) => `🩸 Blessé — repos forcé (${mmss})`,
    toastInjured: "Tu es blessé, impossible d'agir pour le moment.",
    // Boutique : bâtiments et animaux
    buyLabel: "Acheter",
    shopHorseTitle: (cost) => `🐴 Cheval : ${cost} or`,
    shopHorseSub: "Se déplace bien plus vite une fois enfourché. Approche-toi et appuie sur F (peut porter deux cavaliers).",
    shopHorseCount: (n, max) => `Chevaux dans la ferme : ${n}/${max}`,
    shopHorseMax: "🐴 Nombre maximum de chevaux atteint.",
    shopWellTitle: (cost) => `🪣 Puits : ${cost} or`,
    shopWellSub: "Ajoute un 2e point de téléport dans les champs (bouton 🪣).",
    shopWellOwned: "🪣 Puits déjà construit.",
    shopAnimalsHeader: "🐮 Marché aux animaux",
    animalRowTitle: (name, cost) => `${name} : ${cost} or`,
    animalRowSub: (prod, sell, hours) => `Produit toutes les ${hours} h : ${prod} (se vend ${sell} or)`,
    penFull: "L'enclos est plein !",
    chatAnimalBought: (name) => `${name} rejoint l'enclos !`,
    promptSellAnimal: (price) => `[E] Vendre l'animal (${price} or)`,
    chatAnimalSold: (name, price) => `💰 ${name} vendu(e) pour ${price} or.`,
    // Bac : productions d'élevage
    prodRowTitle: (name, n) => `${name} × ${n}`,
    fxProduct: (name) => `+1 ${name.toLowerCase()}`,
    fxCollect: "Ramassé !",
    // Minijeu de pêche
    fishBite: (name) => `Ça mord... un ${name.toLowerCase()} !`,
    fishTimingTitle: "🎣 Ferre le poisson !",
    fishTimingHint: "Clique ou Espace quand le curseur est dans la zone verte",
    fishHoldTitle: "🎣 Épuise le poisson !",
    fishHoldHint: "Maintiens (clic ou Espace) pour garder la barre sur le poisson",
    fishReactTitle: "🎣 Prépare-toi...",
    fishReactHint: "Clique DÈS que le cadre devient vert !",
    fishReactNow: "MAINTENANT !",
    fishWin: "Beau poisson !",
    fishFail: "Le poisson s'est échappé...",
    fishTooSoon: "Trop tôt ! Il a filé.",
    // Invites de proximité
    promptShop: "[E] Boutique",
    promptBin: "[E] Vendre",
    promptCoop: "[E] Déposer au chantier",
    promptBarn: "[E] Déposer à la grange",
    promptBarnBuild: "[E] Construire (mini-jeu)",
    promptSleep: "[E] Dormir",
    promptWake: "[E] Se réveiller",
    // Dormir dans la maison (chantier 2026-07)
    toastSleepFull: "Tu n'es pas fatigué, pas besoin de dormir.",
    toastSleepDone: "Bien dormi ! Énergie remplie.",
    toastSleepEarly: "Réveil anticipé.",
    // Trousse de soins (chantier 2026-07) : un autre joueur blessé peut être
    // soigné (touche E à proximité), réduit son repos forcé à 1 minute.
    healKitRowTitle: "🩹 Trousse de soins (gratuite)",
    healKitRowSub: (n) => `Réduit à 1 min le repos forcé d'un coéquipier blessé (approche-toi, touche E). En stock : ${n}`,
    healChat: (healer, hurt) => `🩹 ${healer} a soigné ${hurt}, son repos forcé est réduit à 1 minute !`,
    toastNotInjured: "Ce fermier n'est plus blessé.",
    toastNoHealKit: "Il te faut une trousse de soins (achetable gratuitement au magasin).",
    toastHealTooFar: "Rapproche-toi du fermier blessé pour le soigner.",
    // Grange collaborative persistante (zip 158)
    barnHudLine: (level, max, cap) => `Grange ${level}/${max} · ${cap} animaux max`,
    barnDeposited: (who, n, res) => `${who} apporte ${n} ${res} à la grange.`,
    barnReadyChat: (money) => `🛖 La grange a assez de matériaux, ${money} or ont été prélevés dans la caisse commune : approchez-vous et faites [E] pour construire !`,
    barnBuilt: (who, level) => `🎉 ${who} a fait passer la grange au niveau ${level} !`,
    barnMiniFail: "Raté ! Reviens à la grange pour retenter.",
    barnMiniTitle: (level) => `🔨 Construction de la grange (palier ${level})`,
    barnMiniSub: (hits, needed) => `Coups réussis : ${hits}/${needed}`,
    barnMiniHint: "Clique ou appuie sur Espace quand le curseur est dans la zone verte.",
    toastBarnMax: "La grange est déjà à son niveau maximum.",
    toastFarBarn: "Approche-toi de la grange pour déposer.",
    toastBarnReadyWait: "La grange est prête à être construite : appuie sur E pour lancer le mini-jeu.",
    toastBarnNotReady: "Il manque encore des matériaux avant de pouvoir construire.",
    toastBarnNeedMoney: "Le bois et la pierre sont réunis, mais il manque de l'or dans la caisse commune pour lancer les travaux.",
    // Mission d'équipe (chantier collaboratif, v1)
    coopTitle: "🚧 Mission d'équipe",
    woodLabel: "bois",
    stoneLabel: "pierre",
    coopStarted: (name) => `🚧 Nouvelle mission d'équipe : ${name} ! Apportez du bois et de la pierre au chantier.`,
    coopDeposited: (who, n, res) => `${who} dépose ${n} ${res} au chantier.`,
    coopDone: (name, reward) => `🎉 Mission accomplie : ${name} (+${reward} or) !`,
    toastCoopNone: "Aucune mission d'équipe en cours (revenez à 2 en ligne).",
    toastFarCoop: "Approche-toi du chantier pour déposer.",
    toastCoopNothing: "Tu n'as pas la ressource attendue sur toi (bois ou pierre).",
    // Boutique
    shopTitle: "🛒 Boutique de Pierre",
    shopHint: "Les achats sont payés avec la caisse commune de l'équipe.",
    seedsUsageHint: "Sème une graine sur une case labourée (houe), puis arrose-la (arrosoir équipé : marche dessus, ou vise-la) jusqu'à maturité. L'arrosage reste valable 10h réelles, à renouveler sinon la pousse se met en pause.",
    seedRowSub: (cr) => `Pousse en ${Math.round(cr.growMs / 3600000)} h (arrosée) · se vend ${cr.sell} or · en stock : `,
    seedCostLabel: (cr) => `${cr.seedName} : ${cr.seedCost} or`,
    foodRowTitle: (cost) => `Casse-croûte : ${cost} or`,
    foodRowSub: (e, stock) => `Rend ${e} énergie · en stock : ${stock}`,
    toolsHeader: "⚒ Améliorations d'outils (moins d'énergie, plus efficaces)",
    toolUsage: {
      hoe: "Laboure une case d'herbe pour pouvoir y semer une graine.",
      can: "Arrose une culture plantée pour qu'elle continue de pousser. L'arrosage reste valable 10h réelles, puis il faut réarroser (marcher dessus avec l'arrosoir équipé suffit).",
      axe: "Coupe les arbres pour récolter du bois. Chaque niveau donne aussi ×1,5 plus de bois par arbre.",
      pick: "Casse les rochers pour récolter de la pierre (et parfois une gemme). Chaque niveau donne aussi ×1,5 plus de pierre par rocher.",
    },
    toolRowTitle: (name, lvl) => `${name} : niveau ${lvl}`,
    toolMaxSub: "Niveau maximum atteint !",
    toolUpSub: (lvl, cost) => `Passer au niveau ${lvl} : ${cost} or`,
    buy1: "×1", buy5: "×5", buyOne: "Acheter",
    upgrade: "Améliorer", maxLabel: "MAX",
    fenceRowTitle: (cost) => `Clôture : ${cost} or la section`,
    fenceRowSub: (n) => `Pose ou retire une section où tu veux (touche 8) · en stock : ${n}`,
    lampRowTitle: (cost) => `💡 Lampadaire : ${cost} or`,
    lampRowSub: (n) => `Chantier de 15 min réelles avant d'être fonctionnel, puis éclaire un rayon autour de lui la nuit. Pose ou retire où tu veux (touche 8) · en stock : ${n}`,
    scarecrowRowTitle: (cost) => `🌾 Épouvantail : ${cost} or`,
    scarecrowRowSub: (n) => `Chantier de 10 secondes réelles. Ne bloque pas le passage. Pose ou retire où tu veux (touche 8) · en stock : ${n}`,
    grassRowTitle: (cost) => `🌱 Herbe : ${cost} or l'unité`,
    grassRowSub: (n) => `Replante l'herbe sur une case labourée (chantier de 5 secondes réelles, définitif, pas de retrait) · en stock : ${n}`,
    millRowTitle: (cost) => `🏚️ Moulin : ${cost} or`,
    millRowSub: (n) => `Transforme le blé déposé en sacs de farine, en continu (chantier d'1 heure réelle) · en stock : ${n}`,
    // Bac de vente
    binTitle: "💰 Bac de vente",
    binHint: "L'or gagné va dans la caisse commune de l'équipe.",
    cropRowTitle: (name, n) => `${name} × ${n}`,
    cropRowSub: (cr, n) => `${cr.sell} or pièce · total ${n * cr.sell} or`,
    woodRowTitle: (n) => `Bois × ${n}`,
    stoneRowTitle: (n) => `Pierre × ${n}`,
    perPiece: (v) => `${v} or pièce`,
    sellAll: "Tout vendre",
    // Carte plein écran
    mapTitle: "🗺️ Carte de la vallée",
    mapClose: "Clique n'importe où ou appuie sur Échap ou M pour fermer",
    mapYou: "toi",
    // Boutons flottants
    btnHome: "🏠 Maison",
    btnMap: "🗺️ Carte",
    btnEmployees: "👥 Employés",
    btnChat: "💬 Chat",
    btnLeave: "Quitter",
    homeToast: "🏠 Retour devant la maison !",
    homeBlockedToast: "🌑 Impossible de rentrer d'ici... il faut retrouver le passage.",
    darkPassageToast: "🌑 Une obscurité glaciale t'avale...",
    darkPassageReturnToast: "☀️ Tu retrouves la lumière du jour.",
    evilMonsterCaughtToast: "👹 Une créature t'a happé... tu te réveilles chez toi, blessé.",
    drownToast: "🌊 Glouglou... tu as coulé ! Ramené à la maison, blessé (1 min).",
    // Pommade de protection (chantier 2026-07) : achetable au magasin,
    // repousse les créatures maléfiques et immunise le joueur contre elles
    // pendant 10 minutes, pour explorer/farm côté maléfique sans crainte.
    salveRowTitle: "🧴 Pommade de protection",
    salveRowSub: (n) => `Utilisée : repousse les créatures maléfiques et t'immunise contre elles pendant 10 min. Se fabrique au chaudron (⚗️). En stock : ${n}`,
    salveUseLabel: "Utiliser",
    salveUsedToast: "🧴 Pommade appliquée : immunisé contre les créatures maléfiques pendant 10 minutes.",
    toastNoSalve: "Il te faut une pommade de protection (à fabriquer au chaudron).",
    immunityBanner: (t) => `🧴 Invisible et immunisé aux créatures maléfiques — ${t}`,
    // Chaudron de la pommade de protection (chantier 2026-07) : recette
    // coopérative (1 améthyste + 2 truites + 1 brochet), voir CAULDRON_SITE/
    // SALVE_RECIPE (fermeConstants.js) et resolveSalveDeposit/resolveSalveBrew
    // (fermeEngine.js).
    promptCauldron: "[E] Chaudron (concocter)",
    promptCauldronIgnite: "[E] Allumer le chaudron 🔥",
    promptCauldronBrewing: (s) => `⏳ Concoction en cours... ${s}s`,
    promptCauldronCollect: "[E] Récupérer la pommade",
    promptSalveDeposit: "[E] Déposer poisson au chaudron",
    promptSalveBrew: "[E] Lancer la concoction",
    salveDeposited: (who, n, res) => `${who} dépose ${n} ${res} au chaudron.`,
    salveIgnited: (who) => `🔥 ${who} allume le feu sous le chaudron ! Concoction en cours (1 min)...`,
    salveBrewed: (who) => `⚗️ ${who} récupère une pommade de protection au chaudron !`,
    toastFarCauldron: "Approche-toi du chaudron pour déposer ou concocter.",
    toastNoFishToDeposit: "Tu ne portes ni truite ni brochet à déposer.",
    toastCauldronMissing: "Il manque des ingrédients (1 améthyste, 2 truites, 1 brochet), ou le chaudron n'est pas encore posé.",
    toastCauldronBrewing: "⏳ La concoction est déjà en cours, reviens dans un instant.",
    toastCauldronNothingToCollect: "Rien à récupérer au chaudron pour l'instant.",
    toastCauldronNeedTorch: "Allume d'abord ta torche pour lancer le feu sous le chaudron !",
    toastCauldronHasEnough: "Le chaudron a déjà tout le poisson nécessaire pour cette recette.",
    cauldronNeedAmethyst: "Il manque une améthyste dans la réserve commune de gemmes pour lancer la recette.",
    troutLabel: "truite(s)",
    pikeLabel: "brochet(s)",
    // Menu du chaudron (chantier 2026-07, refonte demande Guillaume : "une
    // fois la recette sélectionnée, le chaudron doit proposer de déposer les
    // ingrédients ? Oui-Non [...] si tous les ingrédients sont là alors on
    // peut cliquer sur prêt ! et puis le chaudron indiquera allumez le
    // chaudron") : liste de produits (une seule entrée pour l'instant),
    // confirmation avant chaque dépôt, bouton "Prêt !" une fois la recette
    // complète, puis allumage effectif dans le monde (clic/E sur le
    // chaudron, torche en main) — voir cauldronPlaceIngredients/
    // igniteCauldron/tryOpenNearby, FermeGame.js.
    cauldronMenuTitle: "⚗️ Que voulez-vous concocter ?",
    cauldronMenuHint: "Réunis les ingrédients du parchemin, puis va allumer ta torche et clique sur le chaudron pour lancer le feu.",
    cauldronProductSalveName: "🧴 Pommade magique",
    // Parchemin de recette (demande Guillaume 2026-07) : nom en haut, liste
    // des ingrédients (avec avancement), effet en bas dans une formulation
    // voilée, sans chiffres de gameplay.
    scrollIngAmethyst: (have, need) => `${need} améthyste de la réserve commune (${have}/${need})`,
    scrollIngTrout: (dep, need) => `${need} truites versées au chaudron (${dep}/${need})`,
    scrollIngPike: (dep, need) => `${need} brochet versé au chaudron (${dep}/${need})`,
    cauldronScrollEffect: "« Qui s'en oint la peau chemine un temps parmi les ombres, et les créatures de la nuit se détournent de son passage. »",
    cauldronAddBtn: "🫗 Ajouter les ingrédients",
    cauldronReadyBtn: "✅ Prêt !",
    cauldronReadyHint: "Recette complète — va allumer ta torche puis clique sur le chaudron pour lancer la concoction !",
    cauldronIgniteHint: "Torche en main, clique sur le chaudron pour allumer le feu et lancer la concoction (1 min).",
    // Chaudron ramené du monde maléfique (chantier 2026-07, demande
    // Guillaume) : artéfact ramassable UNE SEULE fois côté maléfique, puis
    // posable où on veut côté ferme avec l'outil Construction (voir
    // O_CAULDRON/EVIL_CAULDRON_SPAWN, fermeConstants.js).
    promptEvilCauldronPickup: "[E] Ramasser le chaudron",
    evilCauldronPickedToast: "⚗️ Tu as récupéré le chaudron ! Ramène-le côté ferme et pose-le où tu veux (outil Construction).",
    toastCauldronAlreadyTaken: "Ce chaudron a déjà été récupéré.",
    toastNoCauldronStock: "Tu ne portes pas de chaudron à poser.",
    toastCauldronNotEmpty: "Vide le chaudron (poisson déposé) avant de le déplacer.",
    cauldronRowTitle: "⚗️ Chaudron",
    cauldronRowSub: "Ramené du monde maléfique. Pose-le où tu veux avec l'outil Construction : il sert alors à fabriquer la pommade de protection.",
    // Aide
    help1: "ZQSD/WASD/Flèches : bouger (8 directions) · Espace/Clic : utiliser l'outil",
    help2: "1-8 : outils (7 = canne, 8 = clôture) · E : boutique/vente · T : chat · M : carte · 🏠 : maison",
    // Toasts
    toastTired: "Trop de fatigue ! Mange un casse-croûte ou attends demain.",
    toastFarShop: "Approche-toi de la boutique !",
    toastFarBin: "Approche-toi du bac de vente !",
    toastNoGold: "Pas assez d'or !",
    toastToolMax: "Outil au niveau maximum !",
    toastNoFence: "Plus de section de clôture, achètes-en à la boutique !",
    toastNoWood: "Pas assez de bois !",
    toastNoStone: "Pas assez de pierre !",
    toastNoWallStock: "Plus de mur en stock, fabrique-en avec de la pierre !",
    toastNoPathStock: "Plus de dalle en stock, fabrique-en avec de la pierre !",
    toastNoLampStock: "Plus de lampadaire en stock, achètes-en à la boutique !",
    toastNoScarecrowStock: "Plus d'épouvantail en stock, achètes-en à la boutique !",
    toastNoGrassStock: "Plus d'herbe en stock, achètes-en à la boutique !",
    toastNoMillStock: "Plus de moulin en stock, achètes-en un à la boutique !",
    toastMillNotEmpty: "Vide d'abord le moulin (il reste du blé à transformer) avant de le retirer.",
    toastNoWheatToDeposit: "Tu n'as pas de blé récolté à déposer.",
    toastMillFull: "Le moulin est plein de blé, attends qu'il en transforme avant d'en redéposer.",
    toastActionFailed: "Action impossible, réessaie.",
    toastNewDay: (day) => `☀ Jour ${day} ! Énergie restaurée.`,
    // Chat système
    chatWelcome: "Bienvenue sur la ferme ! Appuie sur T pour discuter avec ton équipe.",
    chatToolUp: (name, lvl) => `${name} au niveau ${lvl} !`,
    chatSell: (gain, total) => `Vente : +${gain} or ! Caisse commune : ${total} or`,
    chatNewDay: (day) => `Jour ${day}, bonne journée à la ferme !`,
    chatStormyDay: "Le ciel se couvre... orage et pluie toute la journée, prends un imperméable !",
    chatJoin: (name) => `${name} rejoint la ferme.`,
    chatLeave: (name) => `${name} a quitté la ferme.`,
    // Effets flottants
    fxWood: (n) => `+${n} bois`,
    fxStone: (n) => `+${n} pierre`,
    fxMagicOre: (n) => `+${n} minerai magique`,
    fxHarvest: (name) => `+1 ${name.toLowerCase()}`,
    fxGold: (n) => `+${n} or`,
    fxEat: "Miam !",
    chatSend: "Message… (Entrée pour envoyer)",
    hireLabel: "Engager",
    gregRowTitle: (cost) => `🧑‍🌾 Engager Greg : ${cost} or`,
    gregRowSub: "Employé de champs — arrose tout automatiquement toutes les 10h, et exécute tes ordres de labour/plantation.",
    gregNotHiredSub: "Contrat de 2 jours",
    gregHiredUntil: (h) => `Employé — encore ${h}h de contrat`,
    gregOrderBtn: "Donner un ordre",
    gregOrderTitle: "Ordonner à Greg de labourer, planter puis arroser",
    gregOrderCountLabel: "Nombre de cases",
    gregOrderCost: (n) => `Coût : ${n} or`,
    gregOrderHint: "Greg labourera intelligemment autour de l'endroit où tu te trouveras quand tu lanceras l'ordre.",
    gregOrderArmBtn: "Choisir cet ordre",
    gregOrderFab: "📍 Lancer Greg ici",
    gregOrderCancel: "Annuler l'ordre",
    toastGregNotHired: "Greg n'est pas (ou plus) engagé !",
    toastGregNoRoom: "Greg ne trouve plus de place libre pour ça !",
    toastGregNoFertilizer: "Plus d'engrais en stock !",
    soanRowTitle: (cost) => `🎣 Engager Soan : ${cost} or`,
    soanRowSub: "Employé pêcheur — pêche à la rivière sur ton ordre, peut y rester toute la journée.",
    soanNotHiredSub: "Contrat de 24h",
    soanHiredUntil: (h) => `Employé — encore ${h}h de contrat`,
    soanOrderBtn: "Envoyer pêcher",
    soanRecallBtn: "Rappeler",
    soanStatusRoam: "Se balade, en attente d'ordre",
    soanStatusToRiver: "En route vers la rivière",
    soanStatusFishing: "Pêche à la rivière",
    soanStatusBreak: "En pause, il se balade",
    toastSoanNotHired: "Soan n'est pas (ou plus) engagé !",
    toastSoanNoRiver: "Soan ne trouve pas de rivière accessible !",
    // Menu "Employés actifs" (chantier 2026-07, demande Guillaume) : liste
    // les employés sous contrat, avec accès direct à leurs ordres.
    employeesTitle: "👥 Employés actifs",
    employeesHint: "Les employés sous contrat en ce moment, avec un accès direct pour leur donner un ordre.",
    employeesGregName: "Greg",
    employeesSoanName: "Soan",
    fertilizerShopLabel: "Engrais",
    fertilizerShopBuy: (cost) => `Acheter (${cost} or)`,
    fertilizerShopStock: (n) => `Stock : ${n}`,
    fertilizerOrderBtn: "Épandre de l'engrais",
    fertilizerOrderTitle: "Ordonner à Greg d'épandre de l'engrais",
    fertilizerOrderCost: "Coût : 1 engrais (zone 5x5)",
    fertilizerOrderHint: "Greg accélère la pousse de toutes les cultures déjà plantées dans un carré de 5x5 cases autour de l'endroit où tu te trouveras quand tu lanceras l'ordre.",
    fertilizerOrderArmBtn: "Choisir cet ordre",
    fertilizerOrderAvailable: (n) => `Engrais disponible : ${n}`,
  },
  en: {
    codeTitle: "🌾 Valley Farm",
    codePrompt: "Enter a farm code to continue an existing game, or a new code to start a new farm. The same code always reloads the same farm.",
    codePlaceholder: "Farm code (e.g. garden)",
    codeLoad: "Open the farm",
    codeLoading: "Loading the farm…",
    codeEmpty: "Choose a farm code.",
    codeDbError: "Farm saves unavailable. Did you run supabase/upgrade-005.sql?",
    csTitle: "🌾 Valley Farm",
    csSub: "Co-op farm: grow, chop, mine and sell with your team.",
    btnChangeChar: "🧑‍🌾 Change character",
    namePlaceholder: "Your farmer name",
    fermier: "Farmer (M)",
    fermiere: "Farmer (F)",
    joinBtn: "Join the farm!",
    connecting: "Connecting to the farm…",
    waitWorld: "Waiting for the host to open the farm…",
    goldCommon: "gold (shared pot)",
    day: "Day",
    playersOnline: (n) => `${n} player(s) online`,
    seedsLabel: "Seeds",
    foodLabel: "Snack",
    rodLabel: "Rod",
    seedTip: (name) => `${name} (click to pick another seed)`,
    toolsTip: (name) => `${name} (press 1 to switch tool, click to choose)`,
    foodTip: (e) => `Eat (snack, fish, or an edible animal product)`,
    rodTip: "Fishing rod: aim at the river water to fish",
    fenceTip: "Fence: place or remove a section on the targeted tile (press R to pick its orientation before placing)",
    wallTip: "Wall: place or remove a section on the targeted tile",
    pathTip: "Path: place or remove a tile on the targeted tile",
    bridgeTip: "Bridge: build a bridge tile on a river construction site (permanent, cannot be removed)",
    bridgeRenovateTip: "Renovate to stone: upgrades an already-built wooden bridge tile (stone look, resists nightly decay)",
    lampTip: "Lamp post: place or remove a lamp post on the targeted tile (15 real min to build, then functional: lights up an area at night)",
    scarecrowTip: "Scarecrow: place or remove a scarecrow on the targeted tile (10 real seconds to build). Does not block movement.",
    grassTip: "Grass: replant grass on a tilled tile (5 real seconds to build, permanent, cannot be removed)",
    millTip: "Mill: places a mill (1 real hour to build, continuously turns deposited wheat into flour, can only be removed once empty)",
    herdTip: "Move: click an animal to pick it up, click again to drop it wherever you want",
    fenceDirToast: (kind) => `Fence orientation: ${kind === "h" ? "horizontal" : kind === "v" ? "vertical" : "automatic"}`,
    woodResTip: "Harvested wood: click to build or sell",
    stoneResTip: "Harvested stone: click to build or sell",
    gemsResTip: "Room gems (shared between all players): click to sell",
    flourResTip: "Room flour sacks (shared between all players, produced by mills): click to sell",
    craftMenuTitleWood: (n) => `🪵 Wood: ${n}`,
    craftMenuTitleStone: (n) => `🪨 Stone: ${n}`,
    craftMenuTitleGems: () => `💎 Shared gems`,
    craftMenuTitleFlour: () => `🌾 Shared flour`,
    flourItemName: "Flour sack",
    gemsSharedHint: "Shared between all players on the farm",
    soanFishSharedHint: "Caught by Soan, shared between all players on the farm",
    buildFenceLabel: "Wooden fence",
    buildWallLabel: "Stone wall",
    buildPathLabel: "Paved path",
    buildCostWood: (n) => `${n} wood per section`,
    buildCostStone: (n) => `${n} stone per section`,
    buildCostPath: (n) => `${n} stone per tile`,
    buildBridgeWoodLabel: "Wooden bridge",
    buildBridgeStoneLabel: "Stone bridge",
    buildBridgeRenovateLabel: "Renovate to stone",
    buildCostBridgeWood: (n) => `${n} wood per tile`,
    buildCostBridgeStone: (n) => `${n} stone per tile`,
    equipBtn: "Equip",
    seedMenuTitle: "Choose a seed",
    toolMenuTitle: "Choose a tool",
    toastNeedWater: "Get close to the water and aim at the river to fish!",
    fxGem: (name) => `Gem: ${name}!`,
    fxBridge: "Bridge!",
    fxLeverOpen: "Bridge open!",
    fxLeverClosed: "Bridge closed!",
    fxMillDeposit: (n) => `+${n} wheat deposited`,
    fxFish: (name) => `+1 ${name.toLowerCase()}`,
    questTitle: "🎯 To do: discover the farm",
    questBtn: "🎯 To do",
    questReward: (n) => `+${n} gold`,
    questDone: (label, n) => `Quest done: ${label} (+${n} gold)!`,
    questAllDone: "🎉 Well done, you've covered the farm basics!",
    questLabels: {
      till: "Till a tile (hoe)",
      plant: "Plant a seed",
      water: "Water a crop (watering can)",
      chop: "Chop a tree (axe)",
      mine: "Break a rock (pickaxe)",
      fish: "Catch a fish (rod)",
      sell: "Sell something at the bin",
    },
    btnWell: "🪣 Well",
    whistleTip: "Whistle to call the horses back",
    mountPrompt: "[F] Mount the horse",
    dismountPrompt: "[F] Dismount",
    wellToast: "🪣 Teleported to the well!",
    torchTipOn: "Put out the torch",
    torchTipOff: "Take out a torch (scares wolves away)",
    wolfAteAnimal: () => "A wolf carried off a pen animal tonight!",
    // Aggressive wolves / bite (chantier 2026-07)
    wolfBiteTitle: "🐺 IT'S ATTACKING YOU!",
    wolfBiteHint: "Mash Space (or click) to fight it off!",
    wolfBiteWin: "You fought off the wolf!",
    wolfBiteFailChat: (who) => `🩸 ${who} was bitten by a wolf and dragged back home, injured.`,
    wolfBiteWinChat: (who) => `🐺 ${who} fought off an aggressive wolf!`,
    // Evil creature / bite minigame (chantier 2026-07)
    evilBiteTitle: "👹 IT'S ATTACKING YOU!",
    evilBiteHint: "Mash Space (or click) to break free!",
    evilBiteWin: "You fought off the creature!",
    rabbitCaughtChat: (who) => `🐇 ${who} caught a wild rabbit!`,
    rabbitChallengeOfferTitle: "🐇 Rabbit-catching challenge?",
    rabbitChallengeOfferSub: (n) => `At least 2 farmers are online. Start a challenge: first to catch ${n} rabbits wins a hat!`,
    rabbitChallengeActivate: "Start the challenge",
    rabbitChallengeIgnore: "Ignore",
    rabbitChallengeStarted: (n) => `🐇 Challenge started: first to catch ${n} rabbits wins a hat!`,
    rabbitChallengeWon: (who) => `🎩 ${who} caught 3 rabbits and won the challenge! A hat has been awarded.`,
    rabbitChallengeProgress: (n, target) => `🐇 Rabbit challenge: ${n} / ${target}`,
    injuredBanner: (mmss) => `🩸 Injured — forced rest (${mmss})`,
    toastInjured: "You're injured and can't act right now.",
    buyLabel: "Buy",
    shopHorseTitle: (cost) => `🐴 Horse: ${cost} gold`,
    shopHorseSub: "Moves much faster once mounted. Walk up to it and press F (can carry two riders).",
    shopHorseCount: (n, max) => `Horses on the farm: ${n}/${max}`,
    shopHorseMax: "🐴 Maximum number of horses reached.",
    shopWellTitle: (cost) => `🪣 Well: ${cost} gold`,
    shopWellSub: "Adds a 2nd teleport point in the fields (🪣 button).",
    shopWellOwned: "🪣 Well already built.",
    shopAnimalsHeader: "🐮 Animal market",
    animalRowTitle: (name, cost) => `${name}: ${cost} gold`,
    animalRowSub: (prod, sell, hours) => `Produces every ${hours} h: ${prod} (sells for ${sell} gold)`,
    penFull: "The pen is full!",
    chatAnimalBought: (name) => `${name} joins the pen!`,
    promptSellAnimal: (price) => `[E] Sell the animal (${price} gold)`,
    chatAnimalSold: (name, price) => `💰 ${name} sold for ${price} gold.`,
    prodRowTitle: (name, n) => `${name} × ${n}`,
    fxProduct: (name) => `+1 ${name.toLowerCase()}`,
    fxCollect: "Collected!",
    fishBite: (name) => `A bite... a ${name.toLowerCase()}!`,
    fishTimingTitle: "🎣 Hook the fish!",
    fishTimingHint: "Click or Space when the cursor is in the green zone",
    fishHoldTitle: "🎣 Tire the fish out!",
    fishHoldHint: "Hold (click or Space) to keep the bar on the fish",
    fishReactTitle: "🎣 Get ready...",
    fishReactHint: "Click AS SOON AS the frame turns green!",
    fishReactNow: "NOW!",
    fishWin: "Nice catch!",
    fishFail: "The fish got away...",
    fishTooSoon: "Too soon! It escaped.",
    promptShop: "[E] Shop",
    promptBin: "[E] Sell",
    promptCoop: "[E] Deposit at site",
    promptBarn: "[E] Deposit at barn",
    promptBarnBuild: "[E] Build (mini-game)",
    promptSleep: "[E] Sleep",
    promptWake: "[E] Wake up",
    // Sleeping in the house (2026-07 chantier)
    toastSleepFull: "You're not tired, no need to sleep.",
    toastSleepDone: "Slept well! Energy refilled.",
    toastSleepEarly: "Woke up early.",
    // Heal kit (2026-07 chantier): another injured player can be healed
    // (press E nearby), cutting their forced rest down to 1 minute.
    healKitRowTitle: "🩹 Heal kit (free)",
    healKitRowSub: (n) => `Cuts an injured teammate's forced rest to 1 min (walk up to them, press E). In stock: ${n}`,
    healChat: (healer, hurt) => `🩹 ${healer} healed ${hurt}, forced rest cut down to 1 minute!`,
    toastNotInjured: "That farmer isn't injured anymore.",
    toastNoHealKit: "You need a heal kit (free at the shop).",
    toastHealTooFar: "Get closer to the injured farmer to heal them.",
    // Persistent collaborative barn (zip 158)
    barnHudLine: (level, max, cap) => `Barn ${level}/${max} · ${cap} animals max`,
    barnDeposited: (who, n, res) => `${who} brings ${n} ${res} to the barn.`,
    barnReadyChat: (money) => `🛖 The barn has enough materials, ${money} gold was taken from the shared pot: come over and press [E] to build!`,
    barnBuilt: (who, level) => `🎉 ${who} upgraded the barn to level ${level}!`,
    barnMiniFail: "Missed it! Come back to the barn to try again.",
    barnMiniTitle: (level) => `🔨 Building the barn (tier ${level})`,
    barnMiniSub: (hits, needed) => `Successful hits: ${hits}/${needed}`,
    barnMiniHint: "Click or press Space when the cursor is in the green zone.",
    toastBarnMax: "The barn is already at its maximum level.",
    toastFarBarn: "Get closer to the barn to deposit.",
    toastBarnReadyWait: "The barn is ready to be built: press E to start the mini-game.",
    toastBarnNotReady: "Still missing some materials before you can build.",
    toastBarnNeedMoney: "Wood and stone are ready, but the shared pot doesn't have enough gold to start the work.",
    // Team mission (collaborative construction site, v1)
    coopTitle: "🚧 Team mission",
    woodLabel: "wood",
    stoneLabel: "stone",
    coopStarted: (name) => `🚧 New team mission: ${name}! Bring wood and stone to the site.`,
    coopDeposited: (who, n, res) => `${who} drops ${n} ${res} at the site.`,
    coopDone: (name, reward) => `🎉 Mission complete: ${name} (+${reward} gold)!`,
    toastCoopNone: "No team mission running right now (come back with 2+ online).",
    toastFarCoop: "Get closer to the site to deposit.",
    toastCoopNothing: "You're not carrying the needed resource (wood or stone).",
    shopTitle: "🛒 Pierre's Shop",
    shopHint: "Purchases are paid from the team's shared pot.",
    seedsUsageHint: "Plant a seed on a tilled tile (hoe), then water it (equip the watering can: walk over it, or aim at it) until it's mature. Watering stays valid for 10 real hours; renew it or growth pauses.",
    seedRowSub: (cr) => `Grows in ${Math.round(cr.growMs / 3600000)} h (watered) · sells for ${cr.sell} gold · in stock: `,
    seedCostLabel: (cr) => `${cr.seedNameEn} : ${cr.seedCost} gold`,
    foodRowTitle: (cost) => `Snack: ${cost} gold`,
    foodRowSub: (e, stock) => `Restores ${e} energy · in stock: ${stock}`,
    toolsHeader: "⚒ Tool upgrades (less energy, more efficient)",
    toolUsage: {
      hoe: "Tills a grass tile so you can plant a seed on it.",
      can: "Waters a planted crop so it keeps growing. Watering stays valid for 10 real hours, then it needs renewing (walking over it with the can equipped is enough).",
      axe: "Chops trees to harvest wood. Each level also gives ×1.5 more wood per tree.",
      pick: "Breaks rocks to harvest stone (and sometimes a gem). Each level also gives ×1.5 more stone per rock.",
    },
    toolRowTitle: (name, lvl) => `${name}: level ${lvl}`,
    toolMaxSub: "Maximum level reached!",
    toolUpSub: (lvl, cost) => `Upgrade to level ${lvl}: ${cost} gold`,
    buy1: "×1", buy5: "×5", buyOne: "Buy",
    upgrade: "Upgrade", maxLabel: "MAX",
    fenceRowTitle: (cost) => `Fence: ${cost} gold per section`,
    fenceRowSub: (n) => `Place or remove a section anywhere (key 8) · in stock: ${n}`,
    lampRowTitle: (cost) => `💡 Lamp post: ${cost} gold`,
    lampRowSub: (n) => `15 real min to build before it's functional, then lights up an area around it at night. Place or remove anywhere (key 8) · in stock: ${n}`,
    scarecrowRowTitle: (cost) => `🌾 Scarecrow: ${cost} gold`,
    scarecrowRowSub: (n) => `10 real seconds to build. Does not block movement. Place or remove anywhere (key 8) · in stock: ${n}`,
    grassRowTitle: (cost) => `🌱 Grass: ${cost} gold per unit`,
    grassRowSub: (n) => `Replant grass on a tilled tile (5 real seconds to build, permanent, cannot be removed) · in stock: ${n}`,
    millRowTitle: (cost) => `🏚️ Mill: ${cost} gold`,
    millRowSub: (n) => `Continuously turns deposited wheat into flour sacks (1 real hour to build) · in stock: ${n}`,
    binTitle: "💰 Sell bin",
    binHint: "Gold earned goes into the team's shared pot.",
    cropRowTitle: (name, n) => `${name} × ${n}`,
    cropRowSub: (cr, n) => `${cr.sell} gold each · total ${n * cr.sell} gold`,
    woodRowTitle: (n) => `Wood × ${n}`,
    stoneRowTitle: (n) => `Stone × ${n}`,
    perPiece: (v) => `${v} gold each`,
    sellAll: "Sell all",
    mapTitle: "🗺️ Valley map",
    mapClose: "Click anywhere or press Esc or M to close",
    mapYou: "you",
    btnHome: "🏠 House",
    btnMap: "🗺️ Map",
    btnEmployees: "👥 Staff",
    btnChat: "💬 Chat",
    btnLeave: "Leave",
    homeToast: "🏠 Back to the house!",
    homeBlockedToast: "🌑 Can't teleport home from here... find the passage back.",
    darkPassageToast: "🌑 A cold darkness swallows you...",
    darkPassageReturnToast: "☀️ You find daylight again.",
    evilMonsterCaughtToast: "👹 A creature caught you... you wake up at home, injured.",
    drownToast: "🌊 Glub glub... you sank! Carried back home, injured (1 min).",
    // Protection salve (2026-07 chantier): buyable at the shop, repels evil
    // creatures and makes the player immune to them for 10 minutes, so they
    // can explore/farm the evil side without worry.
    salveRowTitle: "🧴 Protection salve",
    salveRowSub: (n) => `When used: repels evil creatures and grants immunity to them for 10 min. Crafted at the cauldron (⚗️). In stock: ${n}`,
    salveUseLabel: "Use",
    salveUsedToast: "🧴 Salve applied: immune to evil creatures for 10 minutes.",
    toastNoSalve: "You need a protection salve (craft it at the cauldron).",
    immunityBanner: (t) => `🧴 Invisible and immune to evil creatures — ${t}`,
    // Protection salve cauldron (2026-07 chantier): cooperative recipe (1
    // amethyst + 2 trout + 1 pike).
    promptCauldron: "[E] Cauldron (brew)",
    promptCauldronIgnite: "[E] Light the cauldron 🔥",
    promptCauldronBrewing: (s) => `⏳ Brewing in progress... ${s}s`,
    promptCauldronCollect: "[E] Collect the salve",
    promptSalveDeposit: "[E] Deposit fish at the cauldron",
    promptSalveBrew: "[E] Start brewing",
    salveDeposited: (who, n, res) => `${who} deposits ${n} ${res} at the cauldron.`,
    salveIgnited: (who) => `🔥 ${who} lights the fire under the cauldron! Brewing in progress (1 min)...`,
    salveBrewed: (who) => `⚗️ ${who} collects a protection salve at the cauldron!`,
    toastFarCauldron: "Get closer to the cauldron to deposit or brew.",
    toastCauldronBrewing: "⏳ Already brewing, come back in a moment.",
    toastCauldronNothingToCollect: "Nothing to collect at the cauldron right now.",
    toastCauldronNeedTorch: "Light your torch first to start the fire under the cauldron!",
    toastCauldronHasEnough: "The cauldron already has all the fish it needs for this recipe.",
    cauldronNeedAmethyst: "The common gem reserve is missing an amethyst to start this recipe.",
    // Cauldron menu (2026-07 chantier, revamp): "deposit ingredients? Yes/No"
    // (becomes "Complete" once the team already started), then a "Ready!"
    // button once the recipe is complete — actually lighting the fire now
    // happens in the world (click/E on the cauldron, torch in hand), not
    // from a menu button. See cauldronPlaceIngredients/igniteCauldron/
    // tryOpenNearby, FermeGame.js.
    cauldronMenuTitle: "⚗️ What would you like to brew?",
    cauldronMenuHint: "Gather the ingredients on the scroll, then go light your torch and click the cauldron to start the fire.",
    cauldronProductSalveName: "🧴 Magic salve",
    scrollIngAmethyst: (have, need) => `${need} amethyst from the common reserve (${have}/${need})`,
    scrollIngTrout: (dep, need) => `${need} trout poured into the cauldron (${dep}/${need})`,
    scrollIngPike: (dep, need) => `${need} pike poured into the cauldron (${dep}/${need})`,
    cauldronScrollEffect: "“Who anoints their skin with it walks a while among the shadows, and the creatures of the night turn away from their path.”",
    cauldronAddBtn: "🫗 Add the ingredients",
    cauldronReadyBtn: "✅ Ready!",
    cauldronReadyHint: "Recipe complete — go light your torch, then click the cauldron to start brewing!",
    cauldronIgniteHint: "Torch in hand, click the cauldron to light the fire and start brewing (1 min).",
    promptEvilCauldronPickup: "[E] Pick up the cauldron",
    evilCauldronPickedToast: "⚗️ You picked up the cauldron! Bring it back to the farm and place it anywhere (Build tool).",
    toastCauldronAlreadyTaken: "This cauldron has already been picked up.",
    toastNoCauldronStock: "You aren't carrying a cauldron to place.",
    toastCauldronNotEmpty: "Empty the cauldron (deposited fish) before moving it.",
    cauldronRowTitle: "⚗️ Cauldron",
    cauldronRowSub: "Brought back from the evil world. Place it anywhere with the Build tool: it's then used to craft the protection salve.",
    toastNoFishToDeposit: "You're not carrying any trout or pike to deposit.",
    toastCauldronMissing: "Missing ingredients (1 amethyst, 2 trout, 1 pike), or the cauldron isn't placed yet.",
    troutLabel: "trout",
    pikeLabel: "pike",
    help1: "WASD/Arrows: move (8 directions) · Space/Click: use tool",
    help2: "1-8: tools (7 = rod, 8 = fence) · E: shop/sell · T: chat · M: map · 🏠: house",
    toastTired: "Too tired! Eat a snack or wait for tomorrow.",
    toastFarShop: "Get closer to the shop!",
    toastFarBin: "Get closer to the sell bin!",
    toastNoGold: "Not enough gold!",
    toastToolMax: "Tool already at max level!",
    toastNoFence: "Out of fence sections, buy more at the shop!",
    toastNoWood: "Not enough wood!",
    toastNoStone: "Not enough stone!",
    toastNoWallStock: "Out of wall sections, craft more from stone!",
    toastNoPathStock: "Out of path tiles, craft more from stone!",
    toastNoLampStock: "Out of lamp posts, buy more at the shop!",
    toastNoScarecrowStock: "Out of scarecrows, buy more at the shop!",
    toastNoGrassStock: "Out of grass, buy more at the shop!",
    toastNoMillStock: "Out of mills, buy one at the shop!",
    toastMillNotEmpty: "Empty the mill first (it still has wheat to grind) before removing it.",
    toastNoWheatToDeposit: "You don't have any harvested wheat to deposit.",
    toastMillFull: "The mill is full of wheat, wait for it to grind some before depositing more.",
    toastActionFailed: "Couldn't do that, try again.",
    toastNewDay: (day) => `☀ Day ${day}! Energy restored.`,
    chatWelcome: "Welcome to the farm! Press T to chat with your team.",
    chatToolUp: (name, lvl) => `${name} upgraded to level ${lvl}!`,
    chatSell: (gain, total) => `Sale: +${gain} gold! Shared pot: ${total} gold`,
    chatNewDay: (day) => `Day ${day}, have a great day on the farm!`,
    chatStormyDay: "The sky is turning grey... storm and rain all day, grab a raincoat!",
    chatJoin: (name) => `${name} joined the farm.`,
    chatLeave: (name) => `${name} left the farm.`,
    fxWood: (n) => `+${n} wood`,
    fxStone: (n) => `+${n} stone`,
    fxMagicOre: (n) => `+${n} magic ore`,
    fxHarvest: (name) => `+1 ${name.toLowerCase()}`,
    fxGold: (n) => `+${n} gold`,
    fxEat: "Yum!",
    chatSend: "Message… (Enter to send)",
    hireLabel: "Hire",
    gregRowTitle: (cost) => `🧑‍🌾 Hire Greg: ${cost} gold`,
    gregRowSub: "Field worker — auto-waters everything every 10h, and carries out your till/plant orders.",
    gregNotHiredSub: "2-day contract",
    gregHiredUntil: (h) => `Hired — ${h}h left on contract`,
    gregOrderBtn: "Give an order",
    gregOrderTitle: "Order Greg to till, plant then water",
    gregOrderCountLabel: "Number of tiles",
    gregOrderCost: (n) => `Cost: ${n} gold`,
    gregOrderHint: "Greg will till smartly around wherever you're standing when you launch the order.",
    gregOrderArmBtn: "Choose this order",
    gregOrderFab: "📍 Send Greg here",
    gregOrderCancel: "Cancel order",
    toastGregNotHired: "Greg isn't hired (anymore)!",
    toastGregNoRoom: "Greg can't find free space for that!",
    toastGregNoFertilizer: "No fertilizer left in stock!",
    soanRowTitle: (cost) => `🎣 Hire Soan: ${cost} gold`,
    soanRowSub: "Fisher — fishes at the river on your order, can stay there all day.",
    soanNotHiredSub: "24h contract",
    soanHiredUntil: (h) => `Hired — ${h}h left on contract`,
    soanOrderBtn: "Send fishing",
    soanRecallBtn: "Recall",
    soanStatusRoam: "Wandering, waiting for orders",
    soanStatusToRiver: "Heading to the river",
    soanStatusFishing: "Fishing at the river",
    soanStatusBreak: "On break, taking a walk",
    toastSoanNotHired: "Soan isn't hired (anymore)!",
    toastSoanNoRiver: "Soan can't find a reachable river!",
    employeesTitle: "👥 Active staff",
    employeesHint: "Employees currently under contract, with direct access to give them an order.",
    employeesGregName: "Greg",
    employeesSoanName: "Soan",
    fertilizerShopLabel: "Fertilizer",
    fertilizerShopBuy: (cost) => `Buy (${cost} gold)`,
    fertilizerShopStock: (n) => `Stock: ${n}`,
    fertilizerOrderBtn: "Spread fertilizer",
    fertilizerOrderTitle: "Order Greg to spread fertilizer",
    fertilizerOrderCost: "Cost: 1 fertilizer (5x5 area)",
    fertilizerOrderHint: "Greg will speed up the growth of every already-planted crop in a 5x5 square around wherever you're standing when you launch the order.",
    fertilizerOrderArmBtn: "Choose this order",
    fertilizerOrderAvailable: (n) => `Fertilizer available: ${n}`,
  },
};

export function fstr(lang) {
  return FERME_STR[lang === "en" ? "en" : "fr"];
}
