export const COPY = {
  fr: {
    solo: "Solo", multiplayer: "Multijoueur",
    soloIntro: "Explorez seul : enchaînez les pays sans vous tromper ou visez cinq lieux avec précision.",
    multiIntro: "De 2 à 8 joueurs devant le même panorama : reconnaissez le pays ou placez le point le plus précis.",
    countryStreak: "Country Streak", countryBattle: "Devinez le pays", pinpoint: "Pinpoint",
    countryStreakDesc: "Une série qui continue tant que le pays est juste.",
    countryBattleDesc: "Cinq pays, un point par bonne réponse, classement final.",
    pinpointSoloDesc: "Cinq manches et un résultat sur 25 000 points.",
    pinpointMultiDesc: "Le meilleur point frappe tous les adversaires moins précis.",
    mapLabel: "Carte", mapLocations: "lieux", noLocationsForMap: "Aucun lieu disponible pour ce mode sur cette carte.",
    answerMethod: "Méthode de réponse", multipleChoice: "QCM de drapeaux", countrySearch: "Recherche complète",
    hp: "Vie initiale", roundTime: "Durée d’une manche", finalTime: "Délai après la première réponse",
    multipliers: "Multiplicateurs", firstBoost: "Première augmentation", increment: "Incrément",
    enabled: "Activés", disabled: "Désactivés", round: "Manche", rounds: "manches", seconds: "secondes", points: "points", pointsShort: "pt",
    reset: "Valeurs par défaut", launchSolo: "Jouer en solo", launchMulti: "Lancer la partie", waitingHost: "L’hôte prépare les règles…",
    invalid: "Vérifiez les valeurs encadrées.", summary: "Résumé",
    countryRule: "Une réponse choisie compte à l’expiration. Le bon pays est révélé après chaque manche.",
    soloScoreRule: "Chaque point vaut jusqu’à 5 000 points ; les cinq manches sont additionnées.",
    damageRule: "Chaque joueur moins précis perd l’écart avec le meilleur score × multiplicateur.",
    multiDamageRule: "Le meilleur score ne perd rien ; chaque autre joueur subit son propre écart en dégâts.",
    untilMistake: "Jusqu’à la première erreur",
    loading: "Préparation du panorama", loaded: "prêt", loadingOne: "charge l’image…",
    loadingSlow: "Le panorama met du temps à répondre. S’il reste vide, utilisez « Panorama indisponible ».",
    fairStart: "Le panorama reste masqué jusqu’au chargement des joueurs présents, puis la manche part pour tous.",
    soloFairStart: "Le panorama reste masqué pendant sa stabilisation, puis la manche commence.",
    externalLimit: "Le chargement Google est externe : l’iframe confirme l’ouverture, pas le dernier pixel. Un délai de stabilisation est appliqué.",
    noKeyTitle: "Clé Street View requise", noKeyBody: "Ajoutez NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY dans .env.local, puis redémarrez le serveur. Utilisez une clé Maps Embed restreinte à vos domaines.",
    noWebglTitle: "Carte de réponse indisponible", noWebglBody: "Ce navigateur ou cet appareil ne peut pas afficher la carte détaillée (WebGL indisponible) : vous ne pourriez jamais poser de point. Essayez un autre navigateur, ou choisissez Country Streak.",
    mapTitle: "Votre réponse", placeHint: "Cliquez ou touchez la carte. Zoomez jusqu’au carrefour, puis confirmez.",
    mapUnavailable: "La carte détaillée nécessite l’accélération graphique du navigateur.",
    expand: "Agrandir la carte", shrink: "Réduire la carte", openMap: "Ouvrir la carte", closeMap: "Rétracter la carte", confirm: "Confirmer ce point", confirmed: "Réponse verrouillée",
    openPanel: "Afficher", closePanel: "Réduire",
    noMarker: "Placez d’abord un marqueur.", firstLocked: "Un joueur a répondu : délai final déclenché.",
    waitingOpponent: "Réponse verrouillée. Les autres jouent encore.", answerLocked: "Réponse verrouillée.", spectating: "Vous observez la suite de la partie.",
    report: "Panorama indisponible", reportConfirm: "Confirmer ?", reportConfirmHint: "La manche sera annulée et un autre lieu chargé.",
    reveal: "Révélation", actual: "Lieu réel", noAnswer: "Aucune réponse", unconfirmed: "Réponse à l’expiration",
    distance: "Distance", tie: "Meilleurs scores égaux : aucun dégât.", next: "Manche suivante",
    rematch: "Rejouer", playAgain: "Nouvelle partie", lobby: "Retour au salon", hostOnly: "En attente de l’hôte…",
    connection: "Synchronisation de la partie…", exhausted: "La sélection de lieux est épuisée : retournez au salon pour relancer.",
    countryMode: "Devinez le pays", whichCountry: "Dans quel pays êtes-vous ?", searchCountry: "Rechercher un pays ou territoire…", peekCountry: "Pays ?",
    noCountry: "Aucun pays ne correspond.", chooseCountry: "Choisissez un pays.", confirmCountry: "Valider ce pays",
    correctCountry: "Le bon pays", correct: "Juste", wrong: "Faux",
    streak: "Série", streakContinues: "Bonne réponse — la série continue !", streakStops: "Mauvaise réponse — la série s’arrête ici.",
    country: "pays", countries: "pays", finalResult: "Résultat final", results: "Résultats", seeResults: "Voir le résultat",
    streakComplete: "Série terminée", fiveRoundsComplete: "Cinq manches terminées", roundScore: "Score de la manche", maxDamage: "Dégâts maximum",
  },
  en: {
    solo: "Solo", multiplayer: "Multiplayer",
    soloIntro: "Explore alone: keep identifying countries or pinpoint five places as accurately as possible.",
    multiIntro: "Two to eight players see the same panorama: identify the country or pinpoint the most accurate location.",
    countryStreak: "Country Streak", countryBattle: "Guess the country", pinpoint: "Pinpoint",
    countryStreakDesc: "Your streak continues for as long as the country is right.",
    countryBattleDesc: "Five countries, one point per correct answer, final ranking.",
    pinpointSoloDesc: "Five rounds and a final score out of 25,000.",
    pinpointMultiDesc: "The closest pin strikes every less accurate opponent.",
    mapLabel: "Map", mapLocations: "locations", noLocationsForMap: "No location available for this mode on this map.",
    answerMethod: "Answer method", multipleChoice: "Flag multiple choice", countrySearch: "Full search",
    hp: "Starting health", roundTime: "Round duration", finalTime: "Delay after the first answer",
    multipliers: "Multipliers", firstBoost: "First increase", increment: "Increment",
    enabled: "Enabled", disabled: "Disabled", round: "Round", rounds: "rounds", seconds: "seconds", points: "points", pointsShort: "pt",
    reset: "Default values", launchSolo: "Play solo", launchMulti: "Start game", waitingHost: "The host is preparing the rules…",
    invalid: "Check the highlighted values.", summary: "Summary",
    countryRule: "A selected answer counts at timeout. The correct country is revealed after every round.",
    soloScoreRule: "Each pin is worth up to 5,000 points; all five rounds are added together.",
    damageRule: "Every less accurate player loses their gap from the best score × multiplier.",
    multiDamageRule: "The best score takes no damage; every other player takes their own score gap.",
    untilMistake: "Until the first mistake",
    loading: "Preparing panorama", loaded: "ready", loadingOne: "is loading the image…",
    loadingSlow: "The panorama is taking a while to respond. If it stays blank, use “Panorama unavailable”.",
    fairStart: "The panorama stays covered until all present players have loaded it, then the round starts for everyone.",
    soloFairStart: "The panorama stays covered while it settles, then the round starts.",
    externalLimit: "Google loads externally: the iframe confirms it opened, not its last pixel. A short settling delay is applied.",
    noKeyTitle: "Street View key required", noKeyBody: "Add NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY to .env.local, then restart the server. Use a Maps Embed key restricted to your domains.",
    noWebglTitle: "Answer map unavailable", noWebglBody: "This browser or device can't display the detailed map (WebGL unavailable): you would never be able to place a point. Try another browser, or choose Country Streak instead.",
    mapTitle: "Your answer", placeHint: "Click or tap the map. Zoom down to the junction, then confirm.",
    mapUnavailable: "The detailed map requires browser graphics acceleration.",
    expand: "Expand map", shrink: "Shrink map", openMap: "Open map", closeMap: "Collapse map", confirm: "Confirm this point", confirmed: "Answer locked",
    openPanel: "Show", closePanel: "Collapse",
    noMarker: "Place a marker first.", firstLocked: "A player answered: final countdown started.",
    waitingOpponent: "Answer locked. The others are still playing.", answerLocked: "Answer locked.", spectating: "You are watching the rest of the game.",
    report: "Panorama unavailable", reportConfirm: "Confirm?", reportConfirmHint: "The round will be voided and another place loaded.",
    reveal: "Reveal", actual: "Actual location", noAnswer: "No answer", unconfirmed: "Answer at timeout",
    distance: "Distance", tie: "Top scores tied: no damage.", next: "Next round",
    rematch: "Play again", playAgain: "New game", lobby: "Back to lobby", hostOnly: "Waiting for the host…",
    connection: "Syncing game…", exhausted: "The location set is exhausted: return to the lobby to start again.",
    countryMode: "Guess the country", whichCountry: "Which country are you in?", searchCountry: "Search a country or territory…", peekCountry: "Country?",
    noCountry: "No country matches.", chooseCountry: "Choose a country.", confirmCountry: "Lock this country",
    correctCountry: "Correct country", correct: "Correct", wrong: "Wrong",
    streak: "Streak", streakContinues: "Correct — the streak continues!", streakStops: "Wrong — the streak ends here.",
    country: "country", countries: "countries", finalResult: "Final result", results: "Results", seeResults: "See result",
    streakComplete: "Streak complete", fiveRoundsComplete: "Five rounds complete", roundScore: "Round score", maxDamage: "Maximum damage",
  },
};

export function copyFor(lang) {
  return COPY[lang] || COPY.fr;
}
