export const COPY = {
  fr: {
    subtitle: "Duel de géolocalisation",
    setupTitle: "Préparez votre expédition",
    setupIntro: "Deux camps, un panorama, une carte. La réponse la plus proche inflige la différence de score en dégâts.",
    hp: "Vie initiale", roundTime: "Durée d’une manche", finalTime: "Délai après la première réponse",
    multipliers: "Multiplicateurs", firstBoost: "Première augmentation", increment: "Incrément",
    enabled: "Activés", disabled: "Désactivés", round: "Manche", seconds: "secondes", points: "points",
    reset: "Valeurs par défaut", launch: "Lancer le duel", waitingHost: "L’hôte prépare les règles du duel…",
    needTwo: "Où’s that ? se joue exactement à deux joueurs connectés.", invalid: "Vérifiez les valeurs encadrées.",
    summary: "Résumé du duel", scoreRule: "5 000 pts jusqu’à 25 m, puis score Arcardi décroissant avec la distance.",
    damageRule: "Dégâts = écart de score × multiplicateur, arrondi à l’entier le plus proche.",
    loading: "Préparation du panorama", loaded: "prêt", loadingOne: "charge l’image…",
    loadingSlow: "Le panorama met du temps à répondre. S’il reste vide, utilisez « Panorama indisponible ».",
    fairStart: "Le panorama reste masqué jusqu’au chargement des deux joueurs, puis la manche part pour tous.",
    externalLimit: "Le chargement Google est externe : l’iframe confirme l’ouverture, pas le dernier pixel. Un délai de stabilisation est appliqué.",
    noKeyTitle: "Clé Street View requise", noKeyBody: "Ajoutez NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY dans .env.local, puis redémarrez le serveur. Utilisez une clé Maps Embed restreinte à vos domaines.",
    mapTitle: "Votre réponse", placeHint: "Cliquez ou touchez la carte. Zoomez jusqu’au carrefour, puis confirmez.",
    expand: "Agrandir la carte", shrink: "Réduire la carte", openMap: "Ouvrir la carte", closeMap: "Rétracter la carte", confirm: "Confirmer ce point", confirmed: "Réponse verrouillée",
    noMarker: "Placez d’abord un marqueur.", firstLocked: "L’adversaire a répondu : délai final déclenché.",
    waitingOpponent: "Réponse verrouillée. L’adversaire joue encore.", report: "Panorama indisponible", reportHint: "La manche sera annulée et un autre lieu chargé.",
    reveal: "Révélation", actual: "Lieu réel", noAnswer: "Aucune réponse", unconfirmed: "Réponse à l’expiration",
    distance: "Distance", score: "Score", damage: "Dégâts", tie: "Scores égaux : aucun dégât.", next: "Manche suivante",
    victory: "Victoire", rematch: "Revanche", lobby: "Retour au salon", hostOnly: "En attente de l’hôte…",
    connection: "Synchronisation du duel…", exhausted: "La sélection de lieux est épuisée : retournez au salon pour relancer un duel.",
  },
  en: {
    subtitle: "Geolocation duel",
    setupTitle: "Prepare your expedition",
    setupIntro: "Two sides, one panorama, one map. The closest answer deals the score difference as damage.",
    hp: "Starting health", roundTime: "Round duration", finalTime: "Delay after the first answer",
    multipliers: "Multipliers", firstBoost: "First increase", increment: "Increment",
    enabled: "Enabled", disabled: "Disabled", round: "Round", seconds: "seconds", points: "points",
    reset: "Default values", launch: "Start the duel", waitingHost: "The host is preparing the duel rules…",
    needTwo: "Où’s that ? requires exactly two connected players.", invalid: "Check the highlighted values.",
    summary: "Duel summary", scoreRule: "5,000 pts up to 25 m, then an Arcardi score decreasing with distance.",
    damageRule: "Damage = score gap × multiplier, rounded to the nearest integer.",
    loading: "Preparing the panorama", loaded: "ready", loadingOne: "is loading the image…",
    loadingSlow: "The panorama is taking a while to respond. If it stays blank, use “Panorama unavailable”.",
    fairStart: "The panorama stays covered until both players have loaded it, then the round starts for everyone.",
    externalLimit: "Google loads externally: the iframe confirms it opened, not its last pixel. A short settling delay is applied.",
    noKeyTitle: "Street View key required", noKeyBody: "Add NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY to .env.local, then restart the server. Use a Maps Embed key restricted to your domains.",
    mapTitle: "Your answer", placeHint: "Click or tap the map. Zoom down to the junction, then confirm.",
    expand: "Expand map", shrink: "Shrink map", openMap: "Open map", closeMap: "Collapse map", confirm: "Confirm this point", confirmed: "Answer locked",
    noMarker: "Place a marker first.", firstLocked: "Your opponent answered: final countdown started.",
    waitingOpponent: "Answer locked. Your opponent is still playing.", report: "Panorama unavailable", reportHint: "The round will be voided and another place loaded.",
    reveal: "Reveal", actual: "Actual location", noAnswer: "No answer", unconfirmed: "Answer at timeout",
    distance: "Distance", score: "Score", damage: "Damage", tie: "Scores tied: no damage.", next: "Next round",
    victory: "Victory", rematch: "Rematch", lobby: "Back to lobby", hostOnly: "Waiting for the host…",
    connection: "Syncing the duel…", exhausted: "The location set is exhausted: return to the lobby to start another duel.",
  },
};

export function copyFor(lang) {
  return COPY[lang] || COPY.fr;
}
